/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables;


import com.elite.cinema.models.Cinema;
import com.elite.cinema.models.Keys;
import com.elite.cinema.models.enums.RefreshmentsCategory;
import com.elite.cinema.models.tables.RefreshmentsOrderDetails.RefreshmentsOrderDetailsPath;
import com.elite.cinema.models.tables.RefreshmentsOrders.RefreshmentsOrdersPath;
import com.elite.cinema.models.tables.records.RefreshmentsRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Refreshments extends TableImpl<RefreshmentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cinema.refreshments</code>
     */
    public static final Refreshments REFRESHMENTS = new Refreshments();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RefreshmentsRecord> getRecordType() {
        return RefreshmentsRecord.class;
    }

    /**
     * The column <code>cinema.refreshments.id</code>.
     */
    public final TableField<RefreshmentsRecord, ULong> ID = createField(DSL.name("id"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>cinema.refreshments.name</code>.
     */
    public final TableField<RefreshmentsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.field(DSL.raw("''"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cinema.refreshments.image</code>.
     */
    public final TableField<RefreshmentsRecord, byte[]> IMAGE = createField(DSL.name("image"), SQLDataType.BLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BLOB)), this, "");

    /**
     * The column <code>cinema.refreshments.price</code>.
     */
    public final TableField<RefreshmentsRecord, UInteger> PRICE = createField(DSL.name("price"), SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>cinema.refreshments.category</code>.
     */
    public final TableField<RefreshmentsRecord, RefreshmentsCategory> CATEGORY = createField(DSL.name("category"), SQLDataType.VARCHAR(6).nullable(false).asEnumDataType(RefreshmentsCategory.class), this, "");

    private Refreshments(Name alias, Table<RefreshmentsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Refreshments(Name alias, Table<RefreshmentsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cinema.refreshments</code> table reference
     */
    public Refreshments(String alias) {
        this(DSL.name(alias), REFRESHMENTS);
    }

    /**
     * Create an aliased <code>cinema.refreshments</code> table reference
     */
    public Refreshments(Name alias) {
        this(alias, REFRESHMENTS);
    }

    /**
     * Create a <code>cinema.refreshments</code> table reference
     */
    public Refreshments() {
        this(DSL.name("refreshments"), null);
    }

    public <O extends Record> Refreshments(Table<O> path, ForeignKey<O, RefreshmentsRecord> childPath, InverseForeignKey<O, RefreshmentsRecord> parentPath) {
        super(path, childPath, parentPath, REFRESHMENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RefreshmentsPath extends Refreshments implements Path<RefreshmentsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RefreshmentsPath(Table<O> path, ForeignKey<O, RefreshmentsRecord> childPath, InverseForeignKey<O, RefreshmentsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RefreshmentsPath(Name alias, Table<RefreshmentsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RefreshmentsPath as(String alias) {
            return new RefreshmentsPath(DSL.name(alias), this);
        }

        @Override
        public RefreshmentsPath as(Name alias) {
            return new RefreshmentsPath(alias, this);
        }

        @Override
        public RefreshmentsPath as(Table<?> alias) {
            return new RefreshmentsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Cinema.CINEMA;
    }

    @Override
    public UniqueKey<RefreshmentsRecord> getPrimaryKey() {
        return Keys.KEY_REFRESHMENTS_PRIMARY;
    }

    private transient RefreshmentsOrderDetailsPath _refreshmentsOrderDetails;

    /**
     * Get the implicit to-many join path to the
     * <code>cinema.refreshments_order_details</code> table
     */
    public RefreshmentsOrderDetailsPath refreshmentsOrderDetails() {
        if (_refreshmentsOrderDetails == null)
            _refreshmentsOrderDetails = new RefreshmentsOrderDetailsPath(this, null, Keys.FK__REFRESHMENTS_REFRESHMENTS.getInverseKey());

        return _refreshmentsOrderDetails;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>cinema.refreshments_orders</code> table
     */
    public RefreshmentsOrdersPath refreshmentsOrders() {
        return refreshmentsOrderDetails().refreshmentsOrders();
    }

    @Override
    public Refreshments as(String alias) {
        return new Refreshments(DSL.name(alias), this);
    }

    @Override
    public Refreshments as(Name alias) {
        return new Refreshments(alias, this);
    }

    @Override
    public Refreshments as(Table<?> alias) {
        return new Refreshments(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Refreshments rename(String name) {
        return new Refreshments(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Refreshments rename(Name name) {
        return new Refreshments(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Refreshments rename(Table<?> name) {
        return new Refreshments(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Refreshments where(Condition condition) {
        return new Refreshments(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Refreshments where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Refreshments where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Refreshments where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Refreshments where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Refreshments where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Refreshments where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Refreshments where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Refreshments whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Refreshments whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
