/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables;


import com.elite.cinema.models.Cinema;
import com.elite.cinema.models.Keys;
import com.elite.cinema.models.tables.Refreshments.RefreshmentsPath;
import com.elite.cinema.models.tables.RefreshmentsOrderDetails.RefreshmentsOrderDetailsPath;
import com.elite.cinema.models.tables.records.RefreshmentsOrdersRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RefreshmentsOrders extends TableImpl<RefreshmentsOrdersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cinema.refreshments_orders</code>
     */
    public static final RefreshmentsOrders REFRESHMENTS_ORDERS = new RefreshmentsOrders();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RefreshmentsOrdersRecord> getRecordType() {
        return RefreshmentsOrdersRecord.class;
    }

    /**
     * The column <code>cinema.refreshments_orders.id</code>.
     */
    public final TableField<RefreshmentsOrdersRecord, ULong> ID = createField(DSL.name("id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>cinema.refreshments_orders.total</code>.
     */
    public final TableField<RefreshmentsOrdersRecord, ULong> TOTAL = createField(DSL.name("total"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>cinema.refreshments_orders.created_at</code>.
     */
    public final TableField<RefreshmentsOrdersRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    private RefreshmentsOrders(Name alias, Table<RefreshmentsOrdersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RefreshmentsOrders(Name alias, Table<RefreshmentsOrdersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cinema.refreshments_orders</code> table reference
     */
    public RefreshmentsOrders(String alias) {
        this(DSL.name(alias), REFRESHMENTS_ORDERS);
    }

    /**
     * Create an aliased <code>cinema.refreshments_orders</code> table reference
     */
    public RefreshmentsOrders(Name alias) {
        this(alias, REFRESHMENTS_ORDERS);
    }

    /**
     * Create a <code>cinema.refreshments_orders</code> table reference
     */
    public RefreshmentsOrders() {
        this(DSL.name("refreshments_orders"), null);
    }

    public <O extends Record> RefreshmentsOrders(Table<O> path, ForeignKey<O, RefreshmentsOrdersRecord> childPath, InverseForeignKey<O, RefreshmentsOrdersRecord> parentPath) {
        super(path, childPath, parentPath, REFRESHMENTS_ORDERS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RefreshmentsOrdersPath extends RefreshmentsOrders implements Path<RefreshmentsOrdersRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RefreshmentsOrdersPath(Table<O> path, ForeignKey<O, RefreshmentsOrdersRecord> childPath, InverseForeignKey<O, RefreshmentsOrdersRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RefreshmentsOrdersPath(Name alias, Table<RefreshmentsOrdersRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RefreshmentsOrdersPath as(String alias) {
            return new RefreshmentsOrdersPath(DSL.name(alias), this);
        }

        @Override
        public RefreshmentsOrdersPath as(Name alias) {
            return new RefreshmentsOrdersPath(alias, this);
        }

        @Override
        public RefreshmentsOrdersPath as(Table<?> alias) {
            return new RefreshmentsOrdersPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Cinema.CINEMA;
    }

    @Override
    public Identity<RefreshmentsOrdersRecord, ULong> getIdentity() {
        return (Identity<RefreshmentsOrdersRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<RefreshmentsOrdersRecord> getPrimaryKey() {
        return Keys.KEY_REFRESHMENTS_ORDERS_PRIMARY;
    }

    private transient RefreshmentsOrderDetailsPath _refreshmentsOrderDetails;

    /**
     * Get the implicit to-many join path to the
     * <code>cinema.refreshments_order_details</code> table
     */
    public RefreshmentsOrderDetailsPath refreshmentsOrderDetails() {
        if (_refreshmentsOrderDetails == null)
            _refreshmentsOrderDetails = new RefreshmentsOrderDetailsPath(this, null, Keys.FK__REFRESHMENTS_DETAILS_ORDERS.getInverseKey());

        return _refreshmentsOrderDetails;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>cinema.refreshments</code> table
     */
    public RefreshmentsPath refreshments() {
        return refreshmentsOrderDetails().refreshments();
    }

    @Override
    public RefreshmentsOrders as(String alias) {
        return new RefreshmentsOrders(DSL.name(alias), this);
    }

    @Override
    public RefreshmentsOrders as(Name alias) {
        return new RefreshmentsOrders(alias, this);
    }

    @Override
    public RefreshmentsOrders as(Table<?> alias) {
        return new RefreshmentsOrders(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RefreshmentsOrders rename(String name) {
        return new RefreshmentsOrders(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RefreshmentsOrders rename(Name name) {
        return new RefreshmentsOrders(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RefreshmentsOrders rename(Table<?> name) {
        return new RefreshmentsOrders(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshmentsOrders where(Condition condition) {
        return new RefreshmentsOrders(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshmentsOrders where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshmentsOrders where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshmentsOrders where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RefreshmentsOrders where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RefreshmentsOrders where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RefreshmentsOrders where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RefreshmentsOrders where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshmentsOrders whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshmentsOrders whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
