/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables;


import com.elite.cinema.models.Cinema;
import com.elite.cinema.models.Keys;
import com.elite.cinema.models.tables.Refreshments.RefreshmentsPath;
import com.elite.cinema.models.tables.RefreshmentsOrders.RefreshmentsOrdersPath;
import com.elite.cinema.models.tables.records.RefreshmentsOrderDetailsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RefreshmentsOrderDetails extends TableImpl<RefreshmentsOrderDetailsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cinema.refreshments_order_details</code>
     */
    public static final RefreshmentsOrderDetails REFRESHMENTS_ORDER_DETAILS = new RefreshmentsOrderDetails();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RefreshmentsOrderDetailsRecord> getRecordType() {
        return RefreshmentsOrderDetailsRecord.class;
    }

    /**
     * The column <code>cinema.refreshments_order_details.order_id</code>.
     */
    public final TableField<RefreshmentsOrderDetailsRecord, ULong> ORDER_ID = createField(DSL.name("order_id"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>cinema.refreshments_order_details.refreshment_id</code>.
     */
    public final TableField<RefreshmentsOrderDetailsRecord, ULong> REFRESHMENT_ID = createField(DSL.name("refreshment_id"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>cinema.refreshments_order_details.quantity</code>.
     */
    public final TableField<RefreshmentsOrderDetailsRecord, UInteger> QUANTITY = createField(DSL.name("quantity"), SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGERUNSIGNED)), this, "");

    private RefreshmentsOrderDetails(Name alias, Table<RefreshmentsOrderDetailsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RefreshmentsOrderDetails(Name alias, Table<RefreshmentsOrderDetailsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cinema.refreshments_order_details</code> table
     * reference
     */
    public RefreshmentsOrderDetails(String alias) {
        this(DSL.name(alias), REFRESHMENTS_ORDER_DETAILS);
    }

    /**
     * Create an aliased <code>cinema.refreshments_order_details</code> table
     * reference
     */
    public RefreshmentsOrderDetails(Name alias) {
        this(alias, REFRESHMENTS_ORDER_DETAILS);
    }

    /**
     * Create a <code>cinema.refreshments_order_details</code> table reference
     */
    public RefreshmentsOrderDetails() {
        this(DSL.name("refreshments_order_details"), null);
    }

    public <O extends Record> RefreshmentsOrderDetails(Table<O> path, ForeignKey<O, RefreshmentsOrderDetailsRecord> childPath, InverseForeignKey<O, RefreshmentsOrderDetailsRecord> parentPath) {
        super(path, childPath, parentPath, REFRESHMENTS_ORDER_DETAILS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RefreshmentsOrderDetailsPath extends RefreshmentsOrderDetails implements Path<RefreshmentsOrderDetailsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RefreshmentsOrderDetailsPath(Table<O> path, ForeignKey<O, RefreshmentsOrderDetailsRecord> childPath, InverseForeignKey<O, RefreshmentsOrderDetailsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RefreshmentsOrderDetailsPath(Name alias, Table<RefreshmentsOrderDetailsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RefreshmentsOrderDetailsPath as(String alias) {
            return new RefreshmentsOrderDetailsPath(DSL.name(alias), this);
        }

        @Override
        public RefreshmentsOrderDetailsPath as(Name alias) {
            return new RefreshmentsOrderDetailsPath(alias, this);
        }

        @Override
        public RefreshmentsOrderDetailsPath as(Table<?> alias) {
            return new RefreshmentsOrderDetailsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Cinema.CINEMA;
    }

    @Override
    public UniqueKey<RefreshmentsOrderDetailsRecord> getPrimaryKey() {
        return Keys.KEY_REFRESHMENTS_ORDER_DETAILS_PRIMARY;
    }

    @Override
    public List<ForeignKey<RefreshmentsOrderDetailsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK__REFRESHMENTS_DETAILS_ORDERS, Keys.FK__REFRESHMENTS_REFRESHMENTS);
    }

    private transient RefreshmentsOrdersPath _refreshmentsOrders;

    /**
     * Get the implicit join path to the <code>cinema.refreshments_orders</code>
     * table.
     */
    public RefreshmentsOrdersPath refreshmentsOrders() {
        if (_refreshmentsOrders == null)
            _refreshmentsOrders = new RefreshmentsOrdersPath(this, Keys.FK__REFRESHMENTS_DETAILS_ORDERS, null);

        return _refreshmentsOrders;
    }

    private transient RefreshmentsPath _refreshments;

    /**
     * Get the implicit join path to the <code>cinema.refreshments</code> table.
     */
    public RefreshmentsPath refreshments() {
        if (_refreshments == null)
            _refreshments = new RefreshmentsPath(this, Keys.FK__REFRESHMENTS_REFRESHMENTS, null);

        return _refreshments;
    }

    @Override
    public RefreshmentsOrderDetails as(String alias) {
        return new RefreshmentsOrderDetails(DSL.name(alias), this);
    }

    @Override
    public RefreshmentsOrderDetails as(Name alias) {
        return new RefreshmentsOrderDetails(alias, this);
    }

    @Override
    public RefreshmentsOrderDetails as(Table<?> alias) {
        return new RefreshmentsOrderDetails(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RefreshmentsOrderDetails rename(String name) {
        return new RefreshmentsOrderDetails(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RefreshmentsOrderDetails rename(Name name) {
        return new RefreshmentsOrderDetails(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RefreshmentsOrderDetails rename(Table<?> name) {
        return new RefreshmentsOrderDetails(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshmentsOrderDetails where(Condition condition) {
        return new RefreshmentsOrderDetails(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshmentsOrderDetails where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshmentsOrderDetails where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshmentsOrderDetails where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RefreshmentsOrderDetails where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RefreshmentsOrderDetails where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RefreshmentsOrderDetails where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RefreshmentsOrderDetails where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshmentsOrderDetails whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshmentsOrderDetails whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
