/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables;


import com.elite.cinema.models.Cinema;
import com.elite.cinema.models.Keys;
import com.elite.cinema.models.tables.Reservations.ReservationsPath;
import com.elite.cinema.models.tables.records.ReservedSeatsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReservedSeats extends TableImpl<ReservedSeatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cinema.reserved_seats</code>
     */
    public static final ReservedSeats RESERVED_SEATS = new ReservedSeats();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReservedSeatsRecord> getRecordType() {
        return ReservedSeatsRecord.class;
    }

    /**
     * The column <code>cinema.reserved_seats.reservation_id</code>.
     */
    public final TableField<ReservedSeatsRecord, ULong> RESERVATION_ID = createField(DSL.name("reservation_id"), SQLDataType.BIGINTUNSIGNED.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINTUNSIGNED)), this, "");

    /**
     * The column <code>cinema.reserved_seats.row</code>.
     */
    public final TableField<ReservedSeatsRecord, UByte> ROW = createField(DSL.name("row"), SQLDataType.TINYINTUNSIGNED.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINTUNSIGNED)), this, "");

    /**
     * The column <code>cinema.reserved_seats.column</code>.
     */
    public final TableField<ReservedSeatsRecord, UByte> COLUMN = createField(DSL.name("column"), SQLDataType.TINYINTUNSIGNED.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINTUNSIGNED)), this, "");

    private ReservedSeats(Name alias, Table<ReservedSeatsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReservedSeats(Name alias, Table<ReservedSeatsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cinema.reserved_seats</code> table reference
     */
    public ReservedSeats(String alias) {
        this(DSL.name(alias), RESERVED_SEATS);
    }

    /**
     * Create an aliased <code>cinema.reserved_seats</code> table reference
     */
    public ReservedSeats(Name alias) {
        this(alias, RESERVED_SEATS);
    }

    /**
     * Create a <code>cinema.reserved_seats</code> table reference
     */
    public ReservedSeats() {
        this(DSL.name("reserved_seats"), null);
    }

    public <O extends Record> ReservedSeats(Table<O> path, ForeignKey<O, ReservedSeatsRecord> childPath, InverseForeignKey<O, ReservedSeatsRecord> parentPath) {
        super(path, childPath, parentPath, RESERVED_SEATS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReservedSeatsPath extends ReservedSeats implements Path<ReservedSeatsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReservedSeatsPath(Table<O> path, ForeignKey<O, ReservedSeatsRecord> childPath, InverseForeignKey<O, ReservedSeatsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReservedSeatsPath(Name alias, Table<ReservedSeatsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReservedSeatsPath as(String alias) {
            return new ReservedSeatsPath(DSL.name(alias), this);
        }

        @Override
        public ReservedSeatsPath as(Name alias) {
            return new ReservedSeatsPath(alias, this);
        }

        @Override
        public ReservedSeatsPath as(Table<?> alias) {
            return new ReservedSeatsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Cinema.CINEMA;
    }

    @Override
    public UniqueKey<ReservedSeatsRecord> getPrimaryKey() {
        return Keys.KEY_RESERVED_SEATS_PRIMARY;
    }

    @Override
    public List<ForeignKey<ReservedSeatsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK__RESERVATIONS);
    }

    private transient ReservationsPath _reservations;

    /**
     * Get the implicit join path to the <code>cinema.reservations</code> table.
     */
    public ReservationsPath reservations() {
        if (_reservations == null)
            _reservations = new ReservationsPath(this, Keys.FK__RESERVATIONS, null);

        return _reservations;
    }

    @Override
    public ReservedSeats as(String alias) {
        return new ReservedSeats(DSL.name(alias), this);
    }

    @Override
    public ReservedSeats as(Name alias) {
        return new ReservedSeats(alias, this);
    }

    @Override
    public ReservedSeats as(Table<?> alias) {
        return new ReservedSeats(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReservedSeats rename(String name) {
        return new ReservedSeats(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReservedSeats rename(Name name) {
        return new ReservedSeats(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReservedSeats rename(Table<?> name) {
        return new ReservedSeats(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReservedSeats where(Condition condition) {
        return new ReservedSeats(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReservedSeats where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReservedSeats where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReservedSeats where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReservedSeats where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReservedSeats where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReservedSeats where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReservedSeats where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReservedSeats whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReservedSeats whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
