/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables;


import com.elite.cinema.models.Cinema;
import com.elite.cinema.models.Keys;
import com.elite.cinema.models.tables.ReservedSeats.ReservedSeatsPath;
import com.elite.cinema.models.tables.Screenings.ScreeningsPath;
import com.elite.cinema.models.tables.records.ReservationsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Reservations extends TableImpl<ReservationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cinema.reservations</code>
     */
    public static final Reservations RESERVATIONS = new Reservations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReservationsRecord> getRecordType() {
        return ReservationsRecord.class;
    }

    /**
     * The column <code>cinema.reservations.id</code>.
     */
    public final TableField<ReservationsRecord, ULong> ID = createField(DSL.name("id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>cinema.reservations.screening_id</code>.
     */
    public final TableField<ReservationsRecord, ULong> SCREENING_ID = createField(DSL.name("screening_id"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>cinema.reservations.total</code>.
     */
    public final TableField<ReservationsRecord, UInteger> TOTAL = createField(DSL.name("total"), SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>cinema.reservations.paid</code>.
     */
    public final TableField<ReservationsRecord, Boolean> PAID = createField(DSL.name("paid"), SQLDataType.BIT.nullable(false).defaultValue(DSL.field(DSL.raw("b'0'"), SQLDataType.BIT)), this, "");

    private Reservations(Name alias, Table<ReservationsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Reservations(Name alias, Table<ReservationsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cinema.reservations</code> table reference
     */
    public Reservations(String alias) {
        this(DSL.name(alias), RESERVATIONS);
    }

    /**
     * Create an aliased <code>cinema.reservations</code> table reference
     */
    public Reservations(Name alias) {
        this(alias, RESERVATIONS);
    }

    /**
     * Create a <code>cinema.reservations</code> table reference
     */
    public Reservations() {
        this(DSL.name("reservations"), null);
    }

    public <O extends Record> Reservations(Table<O> path, ForeignKey<O, ReservationsRecord> childPath, InverseForeignKey<O, ReservationsRecord> parentPath) {
        super(path, childPath, parentPath, RESERVATIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReservationsPath extends Reservations implements Path<ReservationsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReservationsPath(Table<O> path, ForeignKey<O, ReservationsRecord> childPath, InverseForeignKey<O, ReservationsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReservationsPath(Name alias, Table<ReservationsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReservationsPath as(String alias) {
            return new ReservationsPath(DSL.name(alias), this);
        }

        @Override
        public ReservationsPath as(Name alias) {
            return new ReservationsPath(alias, this);
        }

        @Override
        public ReservationsPath as(Table<?> alias) {
            return new ReservationsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Cinema.CINEMA;
    }

    @Override
    public Identity<ReservationsRecord, ULong> getIdentity() {
        return (Identity<ReservationsRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReservationsRecord> getPrimaryKey() {
        return Keys.KEY_RESERVATIONS_PRIMARY;
    }

    @Override
    public List<ForeignKey<ReservationsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_RESERVATIONS_SCREENINGS);
    }

    private transient ScreeningsPath _screenings;

    /**
     * Get the implicit join path to the <code>cinema.screenings</code> table.
     */
    public ScreeningsPath screenings() {
        if (_screenings == null)
            _screenings = new ScreeningsPath(this, Keys.FK_RESERVATIONS_SCREENINGS, null);

        return _screenings;
    }

    private transient ReservedSeatsPath _reservedSeats;

    /**
     * Get the implicit to-many join path to the
     * <code>cinema.reserved_seats</code> table
     */
    public ReservedSeatsPath reservedSeats() {
        if (_reservedSeats == null)
            _reservedSeats = new ReservedSeatsPath(this, null, Keys.FK__RESERVATIONS.getInverseKey());

        return _reservedSeats;
    }

    @Override
    public Reservations as(String alias) {
        return new Reservations(DSL.name(alias), this);
    }

    @Override
    public Reservations as(Name alias) {
        return new Reservations(alias, this);
    }

    @Override
    public Reservations as(Table<?> alias) {
        return new Reservations(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Reservations rename(String name) {
        return new Reservations(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Reservations rename(Name name) {
        return new Reservations(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Reservations rename(Table<?> name) {
        return new Reservations(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reservations where(Condition condition) {
        return new Reservations(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reservations where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reservations where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reservations where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Reservations where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Reservations where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Reservations where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Reservations where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reservations whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reservations whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
