/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables;


import com.elite.cinema.models.Cinema;
import com.elite.cinema.models.tables.records.RevenuesRecord;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Revenues extends TableImpl<RevenuesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cinema.revenues</code>
     */
    public static final Revenues REVENUES = new Revenues();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RevenuesRecord> getRecordType() {
        return RevenuesRecord.class;
    }

    /**
     * The column <code>cinema.revenues.screening_id</code>.
     */
    public final TableField<RevenuesRecord, ULong> SCREENING_ID = createField(DSL.name("screening_id"), SQLDataType.BIGINTUNSIGNED.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINTUNSIGNED)), this, "");

    /**
     * The column <code>cinema.revenues.movie_id</code>.
     */
    public final TableField<RevenuesRecord, ULong> MOVIE_ID = createField(DSL.name("movie_id"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>cinema.revenues.screening_time</code>.
     */
    public final TableField<RevenuesRecord, LocalDateTime> SCREENING_TIME = createField(DSL.name("screening_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>cinema.revenues.total_revenue</code>.
     */
    public final TableField<RevenuesRecord, BigInteger> TOTAL_REVENUE = createField(DSL.name("total_revenue"), SQLDataType.DECIMAL_INTEGER(32).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.DECIMAL_INTEGER)), this, "");

    /**
     * The column <code>cinema.revenues.total_tickets</code>.
     */
    public final TableField<RevenuesRecord, BigInteger> TOTAL_TICKETS = createField(DSL.name("total_tickets"), SQLDataType.DECIMAL_INTEGER(42).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.DECIMAL_INTEGER)), this, "");

    /**
     * The column <code>cinema.revenues.occupancy_rate</code>.
     */
    public final TableField<RevenuesRecord, BigDecimal> OCCUPANCY_RATE = createField(DSL.name("occupancy_rate"), SQLDataType.DECIMAL(46, 4).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.DECIMAL)), this, "");

    private Revenues(Name alias, Table<RevenuesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Revenues(Name alias, Table<RevenuesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("CREATE VIEW `revenues` AS with tickets as (select `r`.`id` AS `reservation_id`,count(0) AS `tickets` from (`cinema`.`reservations` `r` join `cinema`.`reserved_seats` `rs` on(`r`.`id` = `rs`.`reservation_id`)) where `r`.`paid` = 1 group by `r`.`id`)select `s`.`id` AS `screening_id`,`s`.`movie_id` AS `movie_id`,`s`.`screening_time` AS `screening_time`,coalesce(sum(`r`.`total`),0) AS `total_revenue`,coalesce(sum(`t`.`tickets`),0) AS `total_tickets`,coalesce(sum(`t`.`tickets`),0) / 100 AS `occupancy_rate` from (((`cinema`.`screenings` `s` join `cinema`.`movies` `m` on(`s`.`movie_id` = `m`.`id`)) left join `cinema`.`reservations` `r` on(`s`.`id` = `r`.`screening_id`)) left join `tickets` `t` on(`r`.`id` = `t`.`reservation_id`)) group by `s`.`id`"), where);
    }

    /**
     * Create an aliased <code>cinema.revenues</code> table reference
     */
    public Revenues(String alias) {
        this(DSL.name(alias), REVENUES);
    }

    /**
     * Create an aliased <code>cinema.revenues</code> table reference
     */
    public Revenues(Name alias) {
        this(alias, REVENUES);
    }

    /**
     * Create a <code>cinema.revenues</code> table reference
     */
    public Revenues() {
        this(DSL.name("revenues"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Cinema.CINEMA;
    }

    @Override
    public Revenues as(String alias) {
        return new Revenues(DSL.name(alias), this);
    }

    @Override
    public Revenues as(Name alias) {
        return new Revenues(alias, this);
    }

    @Override
    public Revenues as(Table<?> alias) {
        return new Revenues(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Revenues rename(String name) {
        return new Revenues(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Revenues rename(Name name) {
        return new Revenues(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Revenues rename(Table<?> name) {
        return new Revenues(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Revenues where(Condition condition) {
        return new Revenues(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Revenues where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Revenues where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Revenues where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Revenues where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Revenues where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Revenues where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Revenues where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Revenues whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Revenues whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
