/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables;


import com.elite.cinema.models.Cinema;
import com.elite.cinema.models.Keys;
import com.elite.cinema.models.tables.Screenings.ScreeningsPath;
import com.elite.cinema.models.tables.records.ScreeningRoomsRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScreeningRooms extends TableImpl<ScreeningRoomsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cinema.screening_rooms</code>
     */
    public static final ScreeningRooms SCREENING_ROOMS = new ScreeningRooms();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScreeningRoomsRecord> getRecordType() {
        return ScreeningRoomsRecord.class;
    }

    /**
     * The column <code>cinema.screening_rooms.id</code>.
     */
    public final TableField<ScreeningRoomsRecord, ULong> ID = createField(DSL.name("id"), SQLDataType.BIGINTUNSIGNED.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINTUNSIGNED)), this, "");

    /**
     * The column <code>cinema.screening_rooms.name</code>.
     */
    public final TableField<ScreeningRoomsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>cinema.screening_rooms.type</code>.
     */
    public final TableField<ScreeningRoomsRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.CLOB.nullable(false), this, "");

    private ScreeningRooms(Name alias, Table<ScreeningRoomsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ScreeningRooms(Name alias, Table<ScreeningRoomsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cinema.screening_rooms</code> table reference
     */
    public ScreeningRooms(String alias) {
        this(DSL.name(alias), SCREENING_ROOMS);
    }

    /**
     * Create an aliased <code>cinema.screening_rooms</code> table reference
     */
    public ScreeningRooms(Name alias) {
        this(alias, SCREENING_ROOMS);
    }

    /**
     * Create a <code>cinema.screening_rooms</code> table reference
     */
    public ScreeningRooms() {
        this(DSL.name("screening_rooms"), null);
    }

    public <O extends Record> ScreeningRooms(Table<O> path, ForeignKey<O, ScreeningRoomsRecord> childPath, InverseForeignKey<O, ScreeningRoomsRecord> parentPath) {
        super(path, childPath, parentPath, SCREENING_ROOMS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ScreeningRoomsPath extends ScreeningRooms implements Path<ScreeningRoomsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ScreeningRoomsPath(Table<O> path, ForeignKey<O, ScreeningRoomsRecord> childPath, InverseForeignKey<O, ScreeningRoomsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ScreeningRoomsPath(Name alias, Table<ScreeningRoomsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ScreeningRoomsPath as(String alias) {
            return new ScreeningRoomsPath(DSL.name(alias), this);
        }

        @Override
        public ScreeningRoomsPath as(Name alias) {
            return new ScreeningRoomsPath(alias, this);
        }

        @Override
        public ScreeningRoomsPath as(Table<?> alias) {
            return new ScreeningRoomsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Cinema.CINEMA;
    }

    @Override
    public UniqueKey<ScreeningRoomsRecord> getPrimaryKey() {
        return Keys.KEY_SCREENING_ROOMS_PRIMARY;
    }

    private transient ScreeningsPath _screenings;

    /**
     * Get the implicit to-many join path to the <code>cinema.screenings</code>
     * table
     */
    public ScreeningsPath screenings() {
        if (_screenings == null)
            _screenings = new ScreeningsPath(this, null, Keys.FK__SCREENING_ROOMS.getInverseKey());

        return _screenings;
    }

    @Override
    public ScreeningRooms as(String alias) {
        return new ScreeningRooms(DSL.name(alias), this);
    }

    @Override
    public ScreeningRooms as(Name alias) {
        return new ScreeningRooms(alias, this);
    }

    @Override
    public ScreeningRooms as(Table<?> alias) {
        return new ScreeningRooms(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ScreeningRooms rename(String name) {
        return new ScreeningRooms(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ScreeningRooms rename(Name name) {
        return new ScreeningRooms(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ScreeningRooms rename(Table<?> name) {
        return new ScreeningRooms(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScreeningRooms where(Condition condition) {
        return new ScreeningRooms(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScreeningRooms where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScreeningRooms where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScreeningRooms where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ScreeningRooms where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ScreeningRooms where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ScreeningRooms where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ScreeningRooms where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScreeningRooms whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScreeningRooms whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
