/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables;


import com.elite.cinema.models.Cinema;
import com.elite.cinema.models.Keys;
import com.elite.cinema.models.tables.records.SeatsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Seats extends TableImpl<SeatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cinema.seats</code>
     */
    public static final Seats SEATS = new Seats();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SeatsRecord> getRecordType() {
        return SeatsRecord.class;
    }

    /**
     * The column <code>cinema.seats.id</code>.
     */
    public final TableField<SeatsRecord, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>cinema.seats.name</code>.
     */
    public final TableField<SeatsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>cinema.seats.price</code>.
     */
    public final TableField<SeatsRecord, ULong> PRICE = createField(DSL.name("price"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    private Seats(Name alias, Table<SeatsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Seats(Name alias, Table<SeatsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cinema.seats</code> table reference
     */
    public Seats(String alias) {
        this(DSL.name(alias), SEATS);
    }

    /**
     * Create an aliased <code>cinema.seats</code> table reference
     */
    public Seats(Name alias) {
        this(alias, SEATS);
    }

    /**
     * Create a <code>cinema.seats</code> table reference
     */
    public Seats() {
        this(DSL.name("seats"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Cinema.CINEMA;
    }

    @Override
    public UniqueKey<SeatsRecord> getPrimaryKey() {
        return Keys.KEY_SEATS_PRIMARY;
    }

    @Override
    public List<UniqueKey<SeatsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SEATS_NAME);
    }

    @Override
    public Seats as(String alias) {
        return new Seats(DSL.name(alias), this);
    }

    @Override
    public Seats as(Name alias) {
        return new Seats(alias, this);
    }

    @Override
    public Seats as(Table<?> alias) {
        return new Seats(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Seats rename(String name) {
        return new Seats(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Seats rename(Name name) {
        return new Seats(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Seats rename(Table<?> name) {
        return new Seats(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Seats where(Condition condition) {
        return new Seats(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Seats where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Seats where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Seats where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Seats where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Seats where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Seats where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Seats where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Seats whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Seats whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
