/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.pojos;


import com.elite.cinema.models.enums.MoviesRating;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.Arrays;

import org.jooq.types.ULong;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Movies implements Serializable {

    private static final long serialVersionUID = 1L;

    private ULong id;
    private String title;
    private UShort duration;
    private MoviesRating rating;
    private String genre;
    private String director;
    private String description;
    private byte[] poster;
    private Boolean nativeLanguage;
    private LocalDate releaseDate;
    private LocalDate endDate;

    public Movies() {}

    public Movies(Movies value) {
        this.id = value.id;
        this.title = value.title;
        this.duration = value.duration;
        this.rating = value.rating;
        this.genre = value.genre;
        this.director = value.director;
        this.description = value.description;
        this.poster = value.poster;
        this.nativeLanguage = value.nativeLanguage;
        this.releaseDate = value.releaseDate;
        this.endDate = value.endDate;
    }

    public Movies(
        ULong id,
        String title,
        UShort duration,
        MoviesRating rating,
        String genre,
        String director,
        String description,
        byte[] poster,
        Boolean nativeLanguage,
        LocalDate releaseDate,
        LocalDate endDate
    ) {
        this.id = id;
        this.title = title;
        this.duration = duration;
        this.rating = rating;
        this.genre = genre;
        this.director = director;
        this.description = description;
        this.poster = poster;
        this.nativeLanguage = nativeLanguage;
        this.releaseDate = releaseDate;
        this.endDate = endDate;
    }

    /**
     * Getter for <code>cinema.movies.id</code>.
     */
    public ULong getId() {
        return this.id;
    }

    /**
     * Setter for <code>cinema.movies.id</code>.
     */
    public void setId(ULong id) {
        this.id = id;
    }

    /**
     * Getter for <code>cinema.movies.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>cinema.movies.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>cinema.movies.duration</code>.
     */
    public UShort getDuration() {
        return this.duration;
    }

    /**
     * Setter for <code>cinema.movies.duration</code>.
     */
    public void setDuration(UShort duration) {
        this.duration = duration;
    }

    /**
     * Getter for <code>cinema.movies.rating</code>.
     */
    public MoviesRating getRating() {
        return this.rating;
    }

    /**
     * Setter for <code>cinema.movies.rating</code>.
     */
    public void setRating(MoviesRating rating) {
        this.rating = rating;
    }

    /**
     * Getter for <code>cinema.movies.genre</code>.
     */
    public String getGenre() {
        return this.genre;
    }

    /**
     * Setter for <code>cinema.movies.genre</code>.
     */
    public void setGenre(String genre) {
        this.genre = genre;
    }

    /**
     * Getter for <code>cinema.movies.director</code>.
     */
    public String getDirector() {
        return this.director;
    }

    /**
     * Setter for <code>cinema.movies.director</code>.
     */
    public void setDirector(String director) {
        this.director = director;
    }

    /**
     * Getter for <code>cinema.movies.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>cinema.movies.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>cinema.movies.poster</code>.
     */
    public byte[] getPoster() {
        return this.poster;
    }

    /**
     * Setter for <code>cinema.movies.poster</code>.
     */
    public void setPoster(byte[] poster) {
        this.poster = poster;
    }

    /**
     * Getter for <code>cinema.movies.native_language</code>.
     */
    public Boolean getNativeLanguage() {
        return this.nativeLanguage;
    }

    /**
     * Setter for <code>cinema.movies.native_language</code>.
     */
    public void setNativeLanguage(Boolean nativeLanguage) {
        this.nativeLanguage = nativeLanguage;
    }

    /**
     * Getter for <code>cinema.movies.release_date</code>.
     */
    public LocalDate getReleaseDate() {
        return this.releaseDate;
    }

    /**
     * Setter for <code>cinema.movies.release_date</code>.
     */
    public void setReleaseDate(LocalDate releaseDate) {
        this.releaseDate = releaseDate;
    }

    /**
     * Getter for <code>cinema.movies.end_date</code>.
     */
    public LocalDate getEndDate() {
        return this.endDate;
    }

    /**
     * Setter for <code>cinema.movies.end_date</code>.
     */
    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Movies other = (Movies) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.duration == null) {
            if (other.duration != null)
                return false;
        }
        else if (!this.duration.equals(other.duration))
            return false;
        if (this.rating == null) {
            if (other.rating != null)
                return false;
        }
        else if (!this.rating.equals(other.rating))
            return false;
        if (this.genre == null) {
            if (other.genre != null)
                return false;
        }
        else if (!this.genre.equals(other.genre))
            return false;
        if (this.director == null) {
            if (other.director != null)
                return false;
        }
        else if (!this.director.equals(other.director))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.poster == null) {
            if (other.poster != null)
                return false;
        }
        else if (!Arrays.equals(this.poster, other.poster))
            return false;
        if (this.nativeLanguage == null) {
            if (other.nativeLanguage != null)
                return false;
        }
        else if (!this.nativeLanguage.equals(other.nativeLanguage))
            return false;
        if (this.releaseDate == null) {
            if (other.releaseDate != null)
                return false;
        }
        else if (!this.releaseDate.equals(other.releaseDate))
            return false;
        if (this.endDate == null) {
            if (other.endDate != null)
                return false;
        }
        else if (!this.endDate.equals(other.endDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.duration == null) ? 0 : this.duration.hashCode());
        result = prime * result + ((this.rating == null) ? 0 : this.rating.hashCode());
        result = prime * result + ((this.genre == null) ? 0 : this.genre.hashCode());
        result = prime * result + ((this.director == null) ? 0 : this.director.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.poster == null) ? 0 : Arrays.hashCode(this.poster));
        result = prime * result + ((this.nativeLanguage == null) ? 0 : this.nativeLanguage.hashCode());
        result = prime * result + ((this.releaseDate == null) ? 0 : this.releaseDate.hashCode());
        result = prime * result + ((this.endDate == null) ? 0 : this.endDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Movies (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(duration);
        sb.append(", ").append(rating);
        sb.append(", ").append(genre);
        sb.append(", ").append(director);
        sb.append(", ").append(description);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(nativeLanguage);
        sb.append(", ").append(releaseDate);
        sb.append(", ").append(endDate);

        sb.append(")");
        return sb.toString();
    }
}
