/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RefreshmentsOrders implements Serializable {

    private static final long serialVersionUID = 1L;

    private ULong id;
    private ULong total;
    private LocalDateTime createdAt;

    public RefreshmentsOrders() {}

    public RefreshmentsOrders(RefreshmentsOrders value) {
        this.id = value.id;
        this.total = value.total;
        this.createdAt = value.createdAt;
    }

    public RefreshmentsOrders(
        ULong id,
        ULong total,
        LocalDateTime createdAt
    ) {
        this.id = id;
        this.total = total;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>cinema.refreshments_orders.id</code>.
     */
    public ULong getId() {
        return this.id;
    }

    /**
     * Setter for <code>cinema.refreshments_orders.id</code>.
     */
    public void setId(ULong id) {
        this.id = id;
    }

    /**
     * Getter for <code>cinema.refreshments_orders.total</code>.
     */
    public ULong getTotal() {
        return this.total;
    }

    /**
     * Setter for <code>cinema.refreshments_orders.total</code>.
     */
    public void setTotal(ULong total) {
        this.total = total;
    }

    /**
     * Getter for <code>cinema.refreshments_orders.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>cinema.refreshments_orders.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RefreshmentsOrders other = (RefreshmentsOrders) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.total == null) {
            if (other.total != null)
                return false;
        }
        else if (!this.total.equals(other.total))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.total == null) ? 0 : this.total.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RefreshmentsOrders (");

        sb.append(id);
        sb.append(", ").append(total);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
