/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.pojos;


import com.elite.cinema.models.enums.RefreshmentsCategory;

import java.io.Serializable;
import java.util.Arrays;

import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Refreshments implements Serializable {

    private static final long serialVersionUID = 1L;

    private ULong id;
    private String name;
    private byte[] image;
    private UInteger price;
    private RefreshmentsCategory category;

    public Refreshments() {}

    public Refreshments(Refreshments value) {
        this.id = value.id;
        this.name = value.name;
        this.image = value.image;
        this.price = value.price;
        this.category = value.category;
    }

    public Refreshments(
        ULong id,
        String name,
        byte[] image,
        UInteger price,
        RefreshmentsCategory category
    ) {
        this.id = id;
        this.name = name;
        this.image = image;
        this.price = price;
        this.category = category;
    }

    /**
     * Getter for <code>cinema.refreshments.id</code>.
     */
    public ULong getId() {
        return this.id;
    }

    /**
     * Setter for <code>cinema.refreshments.id</code>.
     */
    public void setId(ULong id) {
        this.id = id;
    }

    /**
     * Getter for <code>cinema.refreshments.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>cinema.refreshments.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>cinema.refreshments.image</code>.
     */
    public byte[] getImage() {
        return this.image;
    }

    /**
     * Setter for <code>cinema.refreshments.image</code>.
     */
    public void setImage(byte[] image) {
        this.image = image;
    }

    /**
     * Getter for <code>cinema.refreshments.price</code>.
     */
    public UInteger getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>cinema.refreshments.price</code>.
     */
    public void setPrice(UInteger price) {
        this.price = price;
    }

    /**
     * Getter for <code>cinema.refreshments.category</code>.
     */
    public RefreshmentsCategory getCategory() {
        return this.category;
    }

    /**
     * Setter for <code>cinema.refreshments.category</code>.
     */
    public void setCategory(RefreshmentsCategory category) {
        this.category = category;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Refreshments other = (Refreshments) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.image == null) {
            if (other.image != null)
                return false;
        }
        else if (!Arrays.equals(this.image, other.image))
            return false;
        if (this.price == null) {
            if (other.price != null)
                return false;
        }
        else if (!this.price.equals(other.price))
            return false;
        if (this.category == null) {
            if (other.category != null)
                return false;
        }
        else if (!this.category.equals(other.category))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.image == null) ? 0 : Arrays.hashCode(this.image));
        result = prime * result + ((this.price == null) ? 0 : this.price.hashCode());
        result = prime * result + ((this.category == null) ? 0 : this.category.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Refreshments (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(price);
        sb.append(", ").append(category);

        sb.append(")");
        return sb.toString();
    }
}
