/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.pojos;


import java.io.Serializable;

import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RefreshmentsOrderDetails implements Serializable {

    private static final long serialVersionUID = 1L;

    private ULong orderId;
    private ULong refreshmentId;
    private UInteger quantity;

    public RefreshmentsOrderDetails() {}

    public RefreshmentsOrderDetails(RefreshmentsOrderDetails value) {
        this.orderId = value.orderId;
        this.refreshmentId = value.refreshmentId;
        this.quantity = value.quantity;
    }

    public RefreshmentsOrderDetails(
        ULong orderId,
        ULong refreshmentId,
        UInteger quantity
    ) {
        this.orderId = orderId;
        this.refreshmentId = refreshmentId;
        this.quantity = quantity;
    }

    /**
     * Getter for <code>cinema.refreshments_order_details.order_id</code>.
     */
    public ULong getOrderId() {
        return this.orderId;
    }

    /**
     * Setter for <code>cinema.refreshments_order_details.order_id</code>.
     */
    public void setOrderId(ULong orderId) {
        this.orderId = orderId;
    }

    /**
     * Getter for <code>cinema.refreshments_order_details.refreshment_id</code>.
     */
    public ULong getRefreshmentId() {
        return this.refreshmentId;
    }

    /**
     * Setter for <code>cinema.refreshments_order_details.refreshment_id</code>.
     */
    public void setRefreshmentId(ULong refreshmentId) {
        this.refreshmentId = refreshmentId;
    }

    /**
     * Getter for <code>cinema.refreshments_order_details.quantity</code>.
     */
    public UInteger getQuantity() {
        return this.quantity;
    }

    /**
     * Setter for <code>cinema.refreshments_order_details.quantity</code>.
     */
    public void setQuantity(UInteger quantity) {
        this.quantity = quantity;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RefreshmentsOrderDetails other = (RefreshmentsOrderDetails) obj;
        if (this.orderId == null) {
            if (other.orderId != null)
                return false;
        }
        else if (!this.orderId.equals(other.orderId))
            return false;
        if (this.refreshmentId == null) {
            if (other.refreshmentId != null)
                return false;
        }
        else if (!this.refreshmentId.equals(other.refreshmentId))
            return false;
        if (this.quantity == null) {
            if (other.quantity != null)
                return false;
        }
        else if (!this.quantity.equals(other.quantity))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.orderId == null) ? 0 : this.orderId.hashCode());
        result = prime * result + ((this.refreshmentId == null) ? 0 : this.refreshmentId.hashCode());
        result = prime * result + ((this.quantity == null) ? 0 : this.quantity.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RefreshmentsOrderDetails (");

        sb.append(orderId);
        sb.append(", ").append(refreshmentId);
        sb.append(", ").append(quantity);

        sb.append(")");
        return sb.toString();
    }
}
