/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Reservations implements Serializable {

    private static final long serialVersionUID = 1L;

    private ULong id;
    private ULong screeningId;
    private UInteger total;
    private Boolean paid;
    private LocalDateTime createdAt;

    public Reservations() {}

    public Reservations(Reservations value) {
        this.id = value.id;
        this.screeningId = value.screeningId;
        this.total = value.total;
        this.paid = value.paid;
        this.createdAt = value.createdAt;
    }

    public Reservations(
        ULong id,
        ULong screeningId,
        UInteger total,
        Boolean paid,
        LocalDateTime createdAt
    ) {
        this.id = id;
        this.screeningId = screeningId;
        this.total = total;
        this.paid = paid;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>cinema.reservations.id</code>.
     */
    public ULong getId() {
        return this.id;
    }

    /**
     * Setter for <code>cinema.reservations.id</code>.
     */
    public void setId(ULong id) {
        this.id = id;
    }

    /**
     * Getter for <code>cinema.reservations.screening_id</code>.
     */
    public ULong getScreeningId() {
        return this.screeningId;
    }

    /**
     * Setter for <code>cinema.reservations.screening_id</code>.
     */
    public void setScreeningId(ULong screeningId) {
        this.screeningId = screeningId;
    }

    /**
     * Getter for <code>cinema.reservations.total</code>.
     */
    public UInteger getTotal() {
        return this.total;
    }

    /**
     * Setter for <code>cinema.reservations.total</code>.
     */
    public void setTotal(UInteger total) {
        this.total = total;
    }

    /**
     * Getter for <code>cinema.reservations.paid</code>.
     */
    public Boolean getPaid() {
        return this.paid;
    }

    /**
     * Setter for <code>cinema.reservations.paid</code>.
     */
    public void setPaid(Boolean paid) {
        this.paid = paid;
    }

    /**
     * Getter for <code>cinema.reservations.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>cinema.reservations.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Reservations other = (Reservations) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.screeningId == null) {
            if (other.screeningId != null)
                return false;
        }
        else if (!this.screeningId.equals(other.screeningId))
            return false;
        if (this.total == null) {
            if (other.total != null)
                return false;
        }
        else if (!this.total.equals(other.total))
            return false;
        if (this.paid == null) {
            if (other.paid != null)
                return false;
        }
        else if (!this.paid.equals(other.paid))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.screeningId == null) ? 0 : this.screeningId.hashCode());
        result = prime * result + ((this.total == null) ? 0 : this.total.hashCode());
        result = prime * result + ((this.paid == null) ? 0 : this.paid.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Reservations (");

        sb.append(id);
        sb.append(", ").append(screeningId);
        sb.append(", ").append(total);
        sb.append(", ").append(paid);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
