/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.pojos;


import java.io.Serializable;

import org.jooq.types.UByte;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReservedSeats implements Serializable {

    private static final long serialVersionUID = 1L;

    private ULong reservationId;
    private UByte row;
    private UByte column;

    public ReservedSeats() {}

    public ReservedSeats(ReservedSeats value) {
        this.reservationId = value.reservationId;
        this.row = value.row;
        this.column = value.column;
    }

    public ReservedSeats(
        ULong reservationId,
        UByte row,
        UByte column
    ) {
        this.reservationId = reservationId;
        this.row = row;
        this.column = column;
    }

    /**
     * Getter for <code>cinema.reserved_seats.reservation_id</code>.
     */
    public ULong getReservationId() {
        return this.reservationId;
    }

    /**
     * Setter for <code>cinema.reserved_seats.reservation_id</code>.
     */
    public void setReservationId(ULong reservationId) {
        this.reservationId = reservationId;
    }

    /**
     * Getter for <code>cinema.reserved_seats.row</code>.
     */
    public UByte getRow() {
        return this.row;
    }

    /**
     * Setter for <code>cinema.reserved_seats.row</code>.
     */
    public void setRow(UByte row) {
        this.row = row;
    }

    /**
     * Getter for <code>cinema.reserved_seats.column</code>.
     */
    public UByte getColumn() {
        return this.column;
    }

    /**
     * Setter for <code>cinema.reserved_seats.column</code>.
     */
    public void setColumn(UByte column) {
        this.column = column;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ReservedSeats other = (ReservedSeats) obj;
        if (this.reservationId == null) {
            if (other.reservationId != null)
                return false;
        }
        else if (!this.reservationId.equals(other.reservationId))
            return false;
        if (this.row == null) {
            if (other.row != null)
                return false;
        }
        else if (!this.row.equals(other.row))
            return false;
        if (this.column == null) {
            if (other.column != null)
                return false;
        }
        else if (!this.column.equals(other.column))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.reservationId == null) ? 0 : this.reservationId.hashCode());
        result = prime * result + ((this.row == null) ? 0 : this.row.hashCode());
        result = prime * result + ((this.column == null) ? 0 : this.column.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ReservedSeats (");

        sb.append(reservationId);
        sb.append(", ").append(row);
        sb.append(", ").append(column);

        sb.append(")");
        return sb.toString();
    }
}
