/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDateTime;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Revenues implements Serializable {

    private static final long serialVersionUID = 1L;

    private ULong screeningId;
    private ULong movieId;
    private LocalDateTime screeningTime;
    private BigInteger totalRevenue;
    private BigInteger totalTickets;
    private BigDecimal occupancyRate;

    public Revenues() {}

    public Revenues(Revenues value) {
        this.screeningId = value.screeningId;
        this.movieId = value.movieId;
        this.screeningTime = value.screeningTime;
        this.totalRevenue = value.totalRevenue;
        this.totalTickets = value.totalTickets;
        this.occupancyRate = value.occupancyRate;
    }

    public Revenues(
        ULong screeningId,
        ULong movieId,
        LocalDateTime screeningTime,
        BigInteger totalRevenue,
        BigInteger totalTickets,
        BigDecimal occupancyRate
    ) {
        this.screeningId = screeningId;
        this.movieId = movieId;
        this.screeningTime = screeningTime;
        this.totalRevenue = totalRevenue;
        this.totalTickets = totalTickets;
        this.occupancyRate = occupancyRate;
    }

    /**
     * Getter for <code>cinema.revenues.screening_id</code>.
     */
    public ULong getScreeningId() {
        return this.screeningId;
    }

    /**
     * Setter for <code>cinema.revenues.screening_id</code>.
     */
    public void setScreeningId(ULong screeningId) {
        this.screeningId = screeningId;
    }

    /**
     * Getter for <code>cinema.revenues.movie_id</code>.
     */
    public ULong getMovieId() {
        return this.movieId;
    }

    /**
     * Setter for <code>cinema.revenues.movie_id</code>.
     */
    public void setMovieId(ULong movieId) {
        this.movieId = movieId;
    }

    /**
     * Getter for <code>cinema.revenues.screening_time</code>.
     */
    public LocalDateTime getScreeningTime() {
        return this.screeningTime;
    }

    /**
     * Setter for <code>cinema.revenues.screening_time</code>.
     */
    public void setScreeningTime(LocalDateTime screeningTime) {
        this.screeningTime = screeningTime;
    }

    /**
     * Getter for <code>cinema.revenues.total_revenue</code>.
     */
    public BigInteger getTotalRevenue() {
        return this.totalRevenue;
    }

    /**
     * Setter for <code>cinema.revenues.total_revenue</code>.
     */
    public void setTotalRevenue(BigInteger totalRevenue) {
        this.totalRevenue = totalRevenue;
    }

    /**
     * Getter for <code>cinema.revenues.total_tickets</code>.
     */
    public BigInteger getTotalTickets() {
        return this.totalTickets;
    }

    /**
     * Setter for <code>cinema.revenues.total_tickets</code>.
     */
    public void setTotalTickets(BigInteger totalTickets) {
        this.totalTickets = totalTickets;
    }

    /**
     * Getter for <code>cinema.revenues.occupancy_rate</code>.
     */
    public BigDecimal getOccupancyRate() {
        return this.occupancyRate;
    }

    /**
     * Setter for <code>cinema.revenues.occupancy_rate</code>.
     */
    public void setOccupancyRate(BigDecimal occupancyRate) {
        this.occupancyRate = occupancyRate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Revenues other = (Revenues) obj;
        if (this.screeningId == null) {
            if (other.screeningId != null)
                return false;
        }
        else if (!this.screeningId.equals(other.screeningId))
            return false;
        if (this.movieId == null) {
            if (other.movieId != null)
                return false;
        }
        else if (!this.movieId.equals(other.movieId))
            return false;
        if (this.screeningTime == null) {
            if (other.screeningTime != null)
                return false;
        }
        else if (!this.screeningTime.equals(other.screeningTime))
            return false;
        if (this.totalRevenue == null) {
            if (other.totalRevenue != null)
                return false;
        }
        else if (!this.totalRevenue.equals(other.totalRevenue))
            return false;
        if (this.totalTickets == null) {
            if (other.totalTickets != null)
                return false;
        }
        else if (!this.totalTickets.equals(other.totalTickets))
            return false;
        if (this.occupancyRate == null) {
            if (other.occupancyRate != null)
                return false;
        }
        else if (!this.occupancyRate.equals(other.occupancyRate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.screeningId == null) ? 0 : this.screeningId.hashCode());
        result = prime * result + ((this.movieId == null) ? 0 : this.movieId.hashCode());
        result = prime * result + ((this.screeningTime == null) ? 0 : this.screeningTime.hashCode());
        result = prime * result + ((this.totalRevenue == null) ? 0 : this.totalRevenue.hashCode());
        result = prime * result + ((this.totalTickets == null) ? 0 : this.totalTickets.hashCode());
        result = prime * result + ((this.occupancyRate == null) ? 0 : this.occupancyRate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Revenues (");

        sb.append(screeningId);
        sb.append(", ").append(movieId);
        sb.append(", ").append(screeningTime);
        sb.append(", ").append(totalRevenue);
        sb.append(", ").append(totalTickets);
        sb.append(", ").append(occupancyRate);

        sb.append(")");
        return sb.toString();
    }
}
