/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.pojos;


import com.elite.cinema.models.enums.ScreeningsDisplayType;
import com.elite.cinema.models.enums.ScreeningsTranslationType;

import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Screenings implements Serializable {

    private static final long serialVersionUID = 1L;

    private ULong id;
    private ULong movieId;
    private ULong roomId;
    private LocalDateTime screeningTime;
    private ScreeningsDisplayType displayType;
    private ScreeningsTranslationType translationType;

    public Screenings() {}

    public Screenings(Screenings value) {
        this.id = value.id;
        this.movieId = value.movieId;
        this.roomId = value.roomId;
        this.screeningTime = value.screeningTime;
        this.displayType = value.displayType;
        this.translationType = value.translationType;
    }

    public Screenings(
        ULong id,
        ULong movieId,
        ULong roomId,
        LocalDateTime screeningTime,
        ScreeningsDisplayType displayType,
        ScreeningsTranslationType translationType
    ) {
        this.id = id;
        this.movieId = movieId;
        this.roomId = roomId;
        this.screeningTime = screeningTime;
        this.displayType = displayType;
        this.translationType = translationType;
    }

    /**
     * Getter for <code>cinema.screenings.id</code>.
     */
    public ULong getId() {
        return this.id;
    }

    /**
     * Setter for <code>cinema.screenings.id</code>.
     */
    public void setId(ULong id) {
        this.id = id;
    }

    /**
     * Getter for <code>cinema.screenings.movie_id</code>.
     */
    public ULong getMovieId() {
        return this.movieId;
    }

    /**
     * Setter for <code>cinema.screenings.movie_id</code>.
     */
    public void setMovieId(ULong movieId) {
        this.movieId = movieId;
    }

    /**
     * Getter for <code>cinema.screenings.room_id</code>.
     */
    public ULong getRoomId() {
        return this.roomId;
    }

    /**
     * Setter for <code>cinema.screenings.room_id</code>.
     */
    public void setRoomId(ULong roomId) {
        this.roomId = roomId;
    }

    /**
     * Getter for <code>cinema.screenings.screening_time</code>.
     */
    public LocalDateTime getScreeningTime() {
        return this.screeningTime;
    }

    /**
     * Setter for <code>cinema.screenings.screening_time</code>.
     */
    public void setScreeningTime(LocalDateTime screeningTime) {
        this.screeningTime = screeningTime;
    }

    /**
     * Getter for <code>cinema.screenings.display_type</code>.
     */
    public ScreeningsDisplayType getDisplayType() {
        return this.displayType;
    }

    /**
     * Setter for <code>cinema.screenings.display_type</code>.
     */
    public void setDisplayType(ScreeningsDisplayType displayType) {
        this.displayType = displayType;
    }

    /**
     * Getter for <code>cinema.screenings.translation_type</code>.
     */
    public ScreeningsTranslationType getTranslationType() {
        return this.translationType;
    }

    /**
     * Setter for <code>cinema.screenings.translation_type</code>.
     */
    public void setTranslationType(ScreeningsTranslationType translationType) {
        this.translationType = translationType;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Screenings other = (Screenings) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.movieId == null) {
            if (other.movieId != null)
                return false;
        }
        else if (!this.movieId.equals(other.movieId))
            return false;
        if (this.roomId == null) {
            if (other.roomId != null)
                return false;
        }
        else if (!this.roomId.equals(other.roomId))
            return false;
        if (this.screeningTime == null) {
            if (other.screeningTime != null)
                return false;
        }
        else if (!this.screeningTime.equals(other.screeningTime))
            return false;
        if (this.displayType == null) {
            if (other.displayType != null)
                return false;
        }
        else if (!this.displayType.equals(other.displayType))
            return false;
        if (this.translationType == null) {
            if (other.translationType != null)
                return false;
        }
        else if (!this.translationType.equals(other.translationType))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.movieId == null) ? 0 : this.movieId.hashCode());
        result = prime * result + ((this.roomId == null) ? 0 : this.roomId.hashCode());
        result = prime * result + ((this.screeningTime == null) ? 0 : this.screeningTime.hashCode());
        result = prime * result + ((this.displayType == null) ? 0 : this.displayType.hashCode());
        result = prime * result + ((this.translationType == null) ? 0 : this.translationType.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Screenings (");

        sb.append(id);
        sb.append(", ").append(movieId);
        sb.append(", ").append(roomId);
        sb.append(", ").append(screeningTime);
        sb.append(", ").append(displayType);
        sb.append(", ").append(translationType);

        sb.append(")");
        return sb.toString();
    }
}
