/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.pojos;


import java.io.Serializable;

import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Seats implements Serializable {

    private static final long serialVersionUID = 1L;

    private UInteger id;
    private String name;
    private ULong price;

    public Seats() {}

    public Seats(Seats value) {
        this.id = value.id;
        this.name = value.name;
        this.price = value.price;
    }

    public Seats(
        UInteger id,
        String name,
        ULong price
    ) {
        this.id = id;
        this.name = name;
        this.price = price;
    }

    /**
     * Getter for <code>cinema.seats.id</code>.
     */
    public UInteger getId() {
        return this.id;
    }

    /**
     * Setter for <code>cinema.seats.id</code>.
     */
    public void setId(UInteger id) {
        this.id = id;
    }

    /**
     * Getter for <code>cinema.seats.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>cinema.seats.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>cinema.seats.price</code>.
     */
    public ULong getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>cinema.seats.price</code>.
     */
    public void setPrice(ULong price) {
        this.price = price;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Seats other = (Seats) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.price == null) {
            if (other.price != null)
                return false;
        }
        else if (!this.price.equals(other.price))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.price == null) ? 0 : this.price.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Seats (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(price);

        sb.append(")");
        return sb.toString();
    }
}
