/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.pojos;


import com.elite.cinema.models.enums.UsersType;

import java.io.Serializable;
import java.time.LocalDate;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private ULong id;
    private String name;
    private String phoneNumber;
    private LocalDate dob;
    private String email;
    private String password;
    private UsersType type;

    public Users() {}

    public Users(Users value) {
        this.id = value.id;
        this.name = value.name;
        this.phoneNumber = value.phoneNumber;
        this.dob = value.dob;
        this.email = value.email;
        this.password = value.password;
        this.type = value.type;
    }

    public Users(
        ULong id,
        String name,
        String phoneNumber,
        LocalDate dob,
        String email,
        String password,
        UsersType type
    ) {
        this.id = id;
        this.name = name;
        this.phoneNumber = phoneNumber;
        this.dob = dob;
        this.email = email;
        this.password = password;
        this.type = type;
    }

    /**
     * Getter for <code>cinema.users.id</code>.
     */
    public ULong getId() {
        return this.id;
    }

    /**
     * Setter for <code>cinema.users.id</code>.
     */
    public void setId(ULong id) {
        this.id = id;
    }

    /**
     * Getter for <code>cinema.users.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>cinema.users.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>cinema.users.phone_number</code>.
     */
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    /**
     * Setter for <code>cinema.users.phone_number</code>.
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * Getter for <code>cinema.users.dob</code>.
     */
    public LocalDate getDob() {
        return this.dob;
    }

    /**
     * Setter for <code>cinema.users.dob</code>.
     */
    public void setDob(LocalDate dob) {
        this.dob = dob;
    }

    /**
     * Getter for <code>cinema.users.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>cinema.users.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>cinema.users.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>cinema.users.password</code>.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Getter for <code>cinema.users.type</code>.
     */
    public UsersType getType() {
        return this.type;
    }

    /**
     * Setter for <code>cinema.users.type</code>.
     */
    public void setType(UsersType type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Users other = (Users) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.phoneNumber == null) {
            if (other.phoneNumber != null)
                return false;
        }
        else if (!this.phoneNumber.equals(other.phoneNumber))
            return false;
        if (this.dob == null) {
            if (other.dob != null)
                return false;
        }
        else if (!this.dob.equals(other.dob))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.password == null) {
            if (other.password != null)
                return false;
        }
        else if (!this.password.equals(other.password))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.phoneNumber == null) ? 0 : this.phoneNumber.hashCode());
        result = prime * result + ((this.dob == null) ? 0 : this.dob.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(phoneNumber);
        sb.append(", ").append(dob);
        sb.append(", ").append(email);
        sb.append(", ").append(password);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
