/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.records;


import com.elite.cinema.models.tables.MovieInformations;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MovieInformationsRecord extends UpdatableRecordImpl<MovieInformationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cinema.movie_informations.movie_id</code>.
     */
    public void setMovieId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>cinema.movie_informations.movie_id</code>.
     */
    public ULong getMovieId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>cinema.movie_informations.genre</code>.
     */
    public void setGenre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cinema.movie_informations.genre</code>.
     */
    public String getGenre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cinema.movie_informations.release_date</code>.
     */
    public void setReleaseDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>cinema.movie_informations.release_date</code>.
     */
    public LocalDate getReleaseDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>cinema.movie_informations.director</code>.
     */
    public void setDirector(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cinema.movie_informations.director</code>.
     */
    public String getDirector() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cinema.movie_informations.rating</code>.
     */
    public void setRating(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cinema.movie_informations.rating</code>.
     */
    public String getRating() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cinema.movie_informations.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cinema.movie_informations.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MovieInformationsRecord
     */
    public MovieInformationsRecord() {
        super(MovieInformations.MOVIE_INFORMATIONS);
    }

    /**
     * Create a detached, initialised MovieInformationsRecord
     */
    public MovieInformationsRecord(ULong movieId, String genre, LocalDate releaseDate, String director, String rating, String description) {
        super(MovieInformations.MOVIE_INFORMATIONS);

        setMovieId(movieId);
        setGenre(genre);
        setReleaseDate(releaseDate);
        setDirector(director);
        setRating(rating);
        setDescription(description);
        resetTouchedOnNotNull();
    }
}
