/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.records;


import com.elite.cinema.models.tables.Movies;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MoviesRecord extends UpdatableRecordImpl<MoviesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cinema.movies.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>cinema.movies.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>cinema.movies.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cinema.movies.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cinema.movies.duration</code>.
     */
    public void setDuration(UShort value) {
        set(2, value);
    }

    /**
     * Getter for <code>cinema.movies.duration</code>.
     */
    public UShort getDuration() {
        return (UShort) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MoviesRecord
     */
    public MoviesRecord() {
        super(Movies.MOVIES);
    }

    /**
     * Create a detached, initialised MoviesRecord
     */
    public MoviesRecord(ULong id, String title, UShort duration) {
        super(Movies.MOVIES);

        setId(id);
        setTitle(title);
        setDuration(duration);
        resetTouchedOnNotNull();
    }
}
