/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.records;


import com.elite.cinema.models.tables.RefreshmentsOrders;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RefreshmentsOrdersRecord extends UpdatableRecordImpl<RefreshmentsOrdersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cinema.refreshments_orders.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>cinema.refreshments_orders.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>cinema.refreshments_orders.total</code>.
     */
    public void setTotal(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>cinema.refreshments_orders.total</code>.
     */
    public ULong getTotal() {
        return (ULong) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RefreshmentsOrdersRecord
     */
    public RefreshmentsOrdersRecord() {
        super(RefreshmentsOrders.REFRESHMENTS_ORDERS);
    }

    /**
     * Create a detached, initialised RefreshmentsOrdersRecord
     */
    public RefreshmentsOrdersRecord(ULong id, ULong total) {
        super(RefreshmentsOrders.REFRESHMENTS_ORDERS);

        setId(id);
        setTotal(total);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised RefreshmentsOrdersRecord
     */
    public RefreshmentsOrdersRecord(com.elite.cinema.models.tables.pojos.RefreshmentsOrders value) {
        super(RefreshmentsOrders.REFRESHMENTS_ORDERS);

        if (value != null) {
            setId(value.getId());
            setTotal(value.getTotal());
            resetTouchedOnNotNull();
        }
    }
}
