/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.records;


import com.elite.cinema.models.tables.RefreshmentsOrderDetails;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RefreshmentsOrderDetailsRecord extends UpdatableRecordImpl<RefreshmentsOrderDetailsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cinema.refreshments_order_details.order_id</code>.
     */
    public void setOrderId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>cinema.refreshments_order_details.order_id</code>.
     */
    public ULong getOrderId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>cinema.refreshments_order_details.refreshment_id</code>.
     */
    public void setRefreshmentId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>cinema.refreshments_order_details.refreshment_id</code>.
     */
    public ULong getRefreshmentId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>cinema.refreshments_order_details.quantity</code>.
     */
    public void setQuantity(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>cinema.refreshments_order_details.quantity</code>.
     */
    public UInteger getQuantity() {
        return (UInteger) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<ULong, ULong> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RefreshmentsOrderDetailsRecord
     */
    public RefreshmentsOrderDetailsRecord() {
        super(RefreshmentsOrderDetails.REFRESHMENTS_ORDER_DETAILS);
    }

    /**
     * Create a detached, initialised RefreshmentsOrderDetailsRecord
     */
    public RefreshmentsOrderDetailsRecord(ULong orderId, ULong refreshmentId, UInteger quantity) {
        super(RefreshmentsOrderDetails.REFRESHMENTS_ORDER_DETAILS);

        setOrderId(orderId);
        setRefreshmentId(refreshmentId);
        setQuantity(quantity);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised RefreshmentsOrderDetailsRecord
     */
    public RefreshmentsOrderDetailsRecord(com.elite.cinema.models.tables.pojos.RefreshmentsOrderDetails value) {
        super(RefreshmentsOrderDetails.REFRESHMENTS_ORDER_DETAILS);

        if (value != null) {
            setOrderId(value.getOrderId());
            setRefreshmentId(value.getRefreshmentId());
            setQuantity(value.getQuantity());
            resetTouchedOnNotNull();
        }
    }
}
