/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.records;


import com.elite.cinema.models.enums.RefreshmentsCategory;
import com.elite.cinema.models.tables.Refreshments;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RefreshmentsRecord extends UpdatableRecordImpl<RefreshmentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cinema.refreshments.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>cinema.refreshments.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>cinema.refreshments.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cinema.refreshments.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cinema.refreshments.image</code>.
     */
    public void setImage(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>cinema.refreshments.image</code>.
     */
    public byte[] getImage() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>cinema.refreshments.price</code>.
     */
    public void setPrice(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>cinema.refreshments.price</code>.
     */
    public UInteger getPrice() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>cinema.refreshments.category</code>.
     */
    public void setCategory(RefreshmentsCategory value) {
        set(4, value);
    }

    /**
     * Getter for <code>cinema.refreshments.category</code>.
     */
    public RefreshmentsCategory getCategory() {
        return (RefreshmentsCategory) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RefreshmentsRecord
     */
    public RefreshmentsRecord() {
        super(Refreshments.REFRESHMENTS);
    }

    /**
     * Create a detached, initialised RefreshmentsRecord
     */
    public RefreshmentsRecord(ULong id, String name, byte[] image, UInteger price, RefreshmentsCategory category) {
        super(Refreshments.REFRESHMENTS);

        setId(id);
        setName(name);
        setImage(image);
        setPrice(price);
        setCategory(category);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised RefreshmentsRecord
     */
    public RefreshmentsRecord(com.elite.cinema.models.tables.pojos.Refreshments value) {
        super(Refreshments.REFRESHMENTS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setImage(value.getImage());
            setPrice(value.getPrice());
            setCategory(value.getCategory());
            resetTouchedOnNotNull();
        }
    }
}
