/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.records;


import com.elite.cinema.models.tables.ReservedSeats;

import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReservedSeatsRecord extends UpdatableRecordImpl<ReservedSeatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cinema.reserved_seats.reservation_id</code>.
     */
    public void setReservationId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>cinema.reserved_seats.reservation_id</code>.
     */
    public ULong getReservationId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>cinema.reserved_seats.row</code>.
     */
    public void setRow(UByte value) {
        set(1, value);
    }

    /**
     * Getter for <code>cinema.reserved_seats.row</code>.
     */
    public UByte getRow() {
        return (UByte) get(1);
    }

    /**
     * Setter for <code>cinema.reserved_seats.column</code>.
     */
    public void setColumn(UByte value) {
        set(2, value);
    }

    /**
     * Getter for <code>cinema.reserved_seats.column</code>.
     */
    public UByte getColumn() {
        return (UByte) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<ULong, UByte, UByte> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReservedSeatsRecord
     */
    public ReservedSeatsRecord() {
        super(ReservedSeats.RESERVED_SEATS);
    }

    /**
     * Create a detached, initialised ReservedSeatsRecord
     */
    public ReservedSeatsRecord(ULong reservationId, UByte row, UByte column) {
        super(ReservedSeats.RESERVED_SEATS);

        setReservationId(reservationId);
        setRow(row);
        setColumn(column);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised ReservedSeatsRecord
     */
    public ReservedSeatsRecord(com.elite.cinema.models.tables.pojos.ReservedSeats value) {
        super(ReservedSeats.RESERVED_SEATS);

        if (value != null) {
            setReservationId(value.getReservationId());
            setRow(value.getRow());
            setColumn(value.getColumn());
            resetTouchedOnNotNull();
        }
    }
}
