/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.records;


import com.elite.cinema.models.tables.Reservations;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReservationsRecord extends UpdatableRecordImpl<ReservationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cinema.reservations.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>cinema.reservations.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>cinema.reservations.screening_id</code>.
     */
    public void setScreeningId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>cinema.reservations.screening_id</code>.
     */
    public ULong getScreeningId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>cinema.reservations.total</code>.
     */
    public void setTotal(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>cinema.reservations.total</code>.
     */
    public UInteger getTotal() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>cinema.reservations.paid</code>.
     */
    public void setPaid(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>cinema.reservations.paid</code>.
     */
    public Boolean getPaid() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>cinema.reservations.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>cinema.reservations.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReservationsRecord
     */
    public ReservationsRecord() {
        super(Reservations.RESERVATIONS);
    }

    /**
     * Create a detached, initialised ReservationsRecord
     */
    public ReservationsRecord(ULong id, ULong screeningId, UInteger total, Boolean paid, LocalDateTime createdAt) {
        super(Reservations.RESERVATIONS);

        setId(id);
        setScreeningId(screeningId);
        setTotal(total);
        setPaid(paid);
        setCreatedAt(createdAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised ReservationsRecord
     */
    public ReservationsRecord(com.elite.cinema.models.tables.pojos.Reservations value) {
        super(Reservations.RESERVATIONS);

        if (value != null) {
            setId(value.getId());
            setScreeningId(value.getScreeningId());
            setTotal(value.getTotal());
            setPaid(value.getPaid());
            setCreatedAt(value.getCreatedAt());
            resetTouchedOnNotNull();
        }
    }
}
