/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.records;


import com.elite.cinema.models.tables.Revenues;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDateTime;

import org.jooq.impl.TableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RevenuesRecord extends TableRecordImpl<RevenuesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cinema.revenues.screening_id</code>.
     */
    public void setScreeningId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>cinema.revenues.screening_id</code>.
     */
    public ULong getScreeningId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>cinema.revenues.movie_id</code>.
     */
    public void setMovieId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>cinema.revenues.movie_id</code>.
     */
    public ULong getMovieId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>cinema.revenues.screening_time</code>.
     */
    public void setScreeningTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>cinema.revenues.screening_time</code>.
     */
    public LocalDateTime getScreeningTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>cinema.revenues.total_revenue</code>.
     */
    public void setTotalRevenue(BigInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>cinema.revenues.total_revenue</code>.
     */
    public BigInteger getTotalRevenue() {
        return (BigInteger) get(3);
    }

    /**
     * Setter for <code>cinema.revenues.total_tickets</code>.
     */
    public void setTotalTickets(BigInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>cinema.revenues.total_tickets</code>.
     */
    public BigInteger getTotalTickets() {
        return (BigInteger) get(4);
    }

    /**
     * Setter for <code>cinema.revenues.occupancy_rate</code>.
     */
    public void setOccupancyRate(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>cinema.revenues.occupancy_rate</code>.
     */
    public BigDecimal getOccupancyRate() {
        return (BigDecimal) get(5);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RevenuesRecord
     */
    public RevenuesRecord() {
        super(Revenues.REVENUES);
    }

    /**
     * Create a detached, initialised RevenuesRecord
     */
    public RevenuesRecord(ULong screeningId, ULong movieId, LocalDateTime screeningTime, BigInteger totalRevenue, BigInteger totalTickets, BigDecimal occupancyRate) {
        super(Revenues.REVENUES);

        setScreeningId(screeningId);
        setMovieId(movieId);
        setScreeningTime(screeningTime);
        setTotalRevenue(totalRevenue);
        setTotalTickets(totalTickets);
        setOccupancyRate(occupancyRate);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised RevenuesRecord
     */
    public RevenuesRecord(com.elite.cinema.models.tables.pojos.Revenues value) {
        super(Revenues.REVENUES);

        if (value != null) {
            setScreeningId(value.getScreeningId());
            setMovieId(value.getMovieId());
            setScreeningTime(value.getScreeningTime());
            setTotalRevenue(value.getTotalRevenue());
            setTotalTickets(value.getTotalTickets());
            setOccupancyRate(value.getOccupancyRate());
            resetTouchedOnNotNull();
        }
    }
}
