/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.records;


import com.elite.cinema.models.tables.ScreeningRooms;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScreeningRoomsRecord extends UpdatableRecordImpl<ScreeningRoomsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cinema.screening_rooms.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>cinema.screening_rooms.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>cinema.screening_rooms.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cinema.screening_rooms.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cinema.screening_rooms.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cinema.screening_rooms.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScreeningRoomsRecord
     */
    public ScreeningRoomsRecord() {
        super(ScreeningRooms.SCREENING_ROOMS);
    }

    /**
     * Create a detached, initialised ScreeningRoomsRecord
     */
    public ScreeningRoomsRecord(ULong id, String name, String type) {
        super(ScreeningRooms.SCREENING_ROOMS);

        setId(id);
        setName(name);
        setType(type);
        resetTouchedOnNotNull();
    }
}
