/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.records;


import com.elite.cinema.models.tables.Seats;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SeatsRecord extends UpdatableRecordImpl<SeatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cinema.seats.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>cinema.seats.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>cinema.seats.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cinema.seats.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cinema.seats.price</code>.
     */
    public void setPrice(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>cinema.seats.price</code>.
     */
    public ULong getPrice() {
        return (ULong) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SeatsRecord
     */
    public SeatsRecord() {
        super(Seats.SEATS);
    }

    /**
     * Create a detached, initialised SeatsRecord
     */
    public SeatsRecord(UInteger id, String name, ULong price) {
        super(Seats.SEATS);

        setId(id);
        setName(name);
        setPrice(price);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised SeatsRecord
     */
    public SeatsRecord(com.elite.cinema.models.tables.pojos.Seats value) {
        super(Seats.SEATS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setPrice(value.getPrice());
            resetTouchedOnNotNull();
        }
    }
}
