/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.records;


import com.elite.cinema.models.enums.UsersType;
import com.elite.cinema.models.tables.Users;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cinema.users.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>cinema.users.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>cinema.users.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cinema.users.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cinema.users.phoneNumber</code>.
     */
    public void setPhonenumber(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cinema.users.phoneNumber</code>.
     */
    public String getPhonenumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cinema.users.dob</code>.
     */
    public void setDob(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>cinema.users.dob</code>.
     */
    public LocalDate getDob() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>cinema.users.email</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cinema.users.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cinema.users.password</code>.
     */
    public void setPassword(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cinema.users.password</code>.
     */
    public String getPassword() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cinema.users.type</code>.
     */
    public void setType(UsersType value) {
        set(6, value);
    }

    /**
     * Getter for <code>cinema.users.type</code>.
     */
    public UsersType getType() {
        return (UsersType) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(ULong id, String name, String phonenumber, LocalDate dob, String email, String password, UsersType type) {
        super(Users.USERS);

        setId(id);
        setName(name);
        setPhonenumber(phonenumber);
        setDob(dob);
        setEmail(email);
        setPassword(password);
        setType(type);
        resetTouchedOnNotNull();
    }
}
