/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.daos;


import com.elite.cinema.models.enums.MoviesRating;
import com.elite.cinema.models.tables.Movies;
import com.elite.cinema.models.tables.records.MoviesRecord;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MoviesDao extends DAOImpl<MoviesRecord, com.elite.cinema.models.tables.pojos.Movies, ULong> {

    /**
     * Create a new MoviesDao without any configuration
     */
    public MoviesDao() {
        super(Movies.MOVIES, com.elite.cinema.models.tables.pojos.Movies.class);
    }

    /**
     * Create a new MoviesDao with an attached configuration
     */
    public MoviesDao(Configuration configuration) {
        super(Movies.MOVIES, com.elite.cinema.models.tables.pojos.Movies.class, configuration);
    }

    @Override
    public ULong getId(com.elite.cinema.models.tables.pojos.Movies object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Movies> fetchRangeOfId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(Movies.MOVIES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Movies> fetchById(ULong... values) {
        return fetch(Movies.MOVIES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.elite.cinema.models.tables.pojos.Movies fetchOneById(ULong value) {
        return fetchOne(Movies.MOVIES.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.elite.cinema.models.tables.pojos.Movies> fetchOptionalById(ULong value) {
        return fetchOptional(Movies.MOVIES.ID, value);
    }

    /**
     * Fetch records that have <code>title BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Movies> fetchRangeOfTitle(String lowerInclusive, String upperInclusive) {
        return fetchRange(Movies.MOVIES.TITLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Movies> fetchByTitle(String... values) {
        return fetch(Movies.MOVIES.TITLE, values);
    }

    /**
     * Fetch records that have <code>duration BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Movies> fetchRangeOfDuration(UShort lowerInclusive, UShort upperInclusive) {
        return fetchRange(Movies.MOVIES.DURATION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>duration IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Movies> fetchByDuration(UShort... values) {
        return fetch(Movies.MOVIES.DURATION, values);
    }

    /**
     * Fetch records that have <code>rating BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Movies> fetchRangeOfRating(MoviesRating lowerInclusive, MoviesRating upperInclusive) {
        return fetchRange(Movies.MOVIES.RATING, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>rating IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Movies> fetchByRating(MoviesRating... values) {
        return fetch(Movies.MOVIES.RATING, values);
    }

    /**
     * Fetch records that have <code>genre BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Movies> fetchRangeOfGenre(String lowerInclusive, String upperInclusive) {
        return fetchRange(Movies.MOVIES.GENRE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>genre IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Movies> fetchByGenre(String... values) {
        return fetch(Movies.MOVIES.GENRE, values);
    }

    /**
     * Fetch records that have <code>director BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Movies> fetchRangeOfDirector(String lowerInclusive, String upperInclusive) {
        return fetchRange(Movies.MOVIES.DIRECTOR, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>director IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Movies> fetchByDirector(String... values) {
        return fetch(Movies.MOVIES.DIRECTOR, values);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Movies> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(Movies.MOVIES.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Movies> fetchByDescription(String... values) {
        return fetch(Movies.MOVIES.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>poster BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Movies> fetchRangeOfPoster(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(Movies.MOVIES.POSTER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>poster IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Movies> fetchByPoster(byte[]... values) {
        return fetch(Movies.MOVIES.POSTER, values);
    }

    /**
     * Fetch records that have <code>native_language BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Movies> fetchRangeOfNativeLanguage(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(Movies.MOVIES.NATIVE_LANGUAGE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>native_language IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Movies> fetchByNativeLanguage(Boolean... values) {
        return fetch(Movies.MOVIES.NATIVE_LANGUAGE, values);
    }

    /**
     * Fetch records that have <code>release_date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Movies> fetchRangeOfReleaseDate(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(Movies.MOVIES.RELEASE_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>release_date IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Movies> fetchByReleaseDate(LocalDate... values) {
        return fetch(Movies.MOVIES.RELEASE_DATE, values);
    }

    /**
     * Fetch records that have <code>end_date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Movies> fetchRangeOfEndDate(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(Movies.MOVIES.END_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>end_date IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Movies> fetchByEndDate(LocalDate... values) {
        return fetch(Movies.MOVIES.END_DATE, values);
    }
}
