/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.daos;


import com.elite.cinema.models.enums.RefreshmentsCategory;
import com.elite.cinema.models.tables.Refreshments;
import com.elite.cinema.models.tables.records.RefreshmentsRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RefreshmentsDao extends DAOImpl<RefreshmentsRecord, com.elite.cinema.models.tables.pojos.Refreshments, ULong> {

    /**
     * Create a new RefreshmentsDao without any configuration
     */
    public RefreshmentsDao() {
        super(Refreshments.REFRESHMENTS, com.elite.cinema.models.tables.pojos.Refreshments.class);
    }

    /**
     * Create a new RefreshmentsDao with an attached configuration
     */
    public RefreshmentsDao(Configuration configuration) {
        super(Refreshments.REFRESHMENTS, com.elite.cinema.models.tables.pojos.Refreshments.class, configuration);
    }

    @Override
    public ULong getId(com.elite.cinema.models.tables.pojos.Refreshments object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Refreshments> fetchRangeOfId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(Refreshments.REFRESHMENTS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Refreshments> fetchById(ULong... values) {
        return fetch(Refreshments.REFRESHMENTS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.elite.cinema.models.tables.pojos.Refreshments fetchOneById(ULong value) {
        return fetchOne(Refreshments.REFRESHMENTS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.elite.cinema.models.tables.pojos.Refreshments> fetchOptionalById(ULong value) {
        return fetchOptional(Refreshments.REFRESHMENTS.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Refreshments> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Refreshments.REFRESHMENTS.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Refreshments> fetchByName(String... values) {
        return fetch(Refreshments.REFRESHMENTS.NAME, values);
    }

    /**
     * Fetch records that have <code>image BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Refreshments> fetchRangeOfImage(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(Refreshments.REFRESHMENTS.IMAGE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>image IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Refreshments> fetchByImage(byte[]... values) {
        return fetch(Refreshments.REFRESHMENTS.IMAGE, values);
    }

    /**
     * Fetch records that have <code>price BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Refreshments> fetchRangeOfPrice(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(Refreshments.REFRESHMENTS.PRICE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>price IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Refreshments> fetchByPrice(UInteger... values) {
        return fetch(Refreshments.REFRESHMENTS.PRICE, values);
    }

    /**
     * Fetch records that have <code>category BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Refreshments> fetchRangeOfCategory(RefreshmentsCategory lowerInclusive, RefreshmentsCategory upperInclusive) {
        return fetchRange(Refreshments.REFRESHMENTS.CATEGORY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>category IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Refreshments> fetchByCategory(RefreshmentsCategory... values) {
        return fetch(Refreshments.REFRESHMENTS.CATEGORY, values);
    }
}
