/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.daos;


import com.elite.cinema.models.tables.RefreshmentsOrderDetails;
import com.elite.cinema.models.tables.records.RefreshmentsOrderDetailsRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RefreshmentsOrderDetailsDao extends DAOImpl<RefreshmentsOrderDetailsRecord, com.elite.cinema.models.tables.pojos.RefreshmentsOrderDetails, Record2<ULong, ULong>> {

    /**
     * Create a new RefreshmentsOrderDetailsDao without any configuration
     */
    public RefreshmentsOrderDetailsDao() {
        super(RefreshmentsOrderDetails.REFRESHMENTS_ORDER_DETAILS, com.elite.cinema.models.tables.pojos.RefreshmentsOrderDetails.class);
    }

    /**
     * Create a new RefreshmentsOrderDetailsDao with an attached configuration
     */
    public RefreshmentsOrderDetailsDao(Configuration configuration) {
        super(RefreshmentsOrderDetails.REFRESHMENTS_ORDER_DETAILS, com.elite.cinema.models.tables.pojos.RefreshmentsOrderDetails.class, configuration);
    }

    @Override
    public Record2<ULong, ULong> getId(com.elite.cinema.models.tables.pojos.RefreshmentsOrderDetails object) {
        return compositeKeyRecord(object.getOrderId(), object.getRefreshmentId());
    }

    /**
     * Fetch records that have <code>order_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.RefreshmentsOrderDetails> fetchRangeOfOrderId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(RefreshmentsOrderDetails.REFRESHMENTS_ORDER_DETAILS.ORDER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>order_id IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.RefreshmentsOrderDetails> fetchByOrderId(ULong... values) {
        return fetch(RefreshmentsOrderDetails.REFRESHMENTS_ORDER_DETAILS.ORDER_ID, values);
    }

    /**
     * Fetch records that have <code>refreshment_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.RefreshmentsOrderDetails> fetchRangeOfRefreshmentId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(RefreshmentsOrderDetails.REFRESHMENTS_ORDER_DETAILS.REFRESHMENT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>refreshment_id IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.RefreshmentsOrderDetails> fetchByRefreshmentId(ULong... values) {
        return fetch(RefreshmentsOrderDetails.REFRESHMENTS_ORDER_DETAILS.REFRESHMENT_ID, values);
    }

    /**
     * Fetch records that have <code>quantity BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.RefreshmentsOrderDetails> fetchRangeOfQuantity(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(RefreshmentsOrderDetails.REFRESHMENTS_ORDER_DETAILS.QUANTITY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>quantity IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.RefreshmentsOrderDetails> fetchByQuantity(UInteger... values) {
        return fetch(RefreshmentsOrderDetails.REFRESHMENTS_ORDER_DETAILS.QUANTITY, values);
    }
}
