/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.daos;


import com.elite.cinema.models.tables.RefreshmentsOrders;
import com.elite.cinema.models.tables.records.RefreshmentsOrdersRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RefreshmentsOrdersDao extends DAOImpl<RefreshmentsOrdersRecord, com.elite.cinema.models.tables.pojos.RefreshmentsOrders, ULong> {

    /**
     * Create a new RefreshmentsOrdersDao without any configuration
     */
    public RefreshmentsOrdersDao() {
        super(RefreshmentsOrders.REFRESHMENTS_ORDERS, com.elite.cinema.models.tables.pojos.RefreshmentsOrders.class);
    }

    /**
     * Create a new RefreshmentsOrdersDao with an attached configuration
     */
    public RefreshmentsOrdersDao(Configuration configuration) {
        super(RefreshmentsOrders.REFRESHMENTS_ORDERS, com.elite.cinema.models.tables.pojos.RefreshmentsOrders.class, configuration);
    }

    @Override
    public ULong getId(com.elite.cinema.models.tables.pojos.RefreshmentsOrders object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.RefreshmentsOrders> fetchRangeOfId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(RefreshmentsOrders.REFRESHMENTS_ORDERS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.RefreshmentsOrders> fetchById(ULong... values) {
        return fetch(RefreshmentsOrders.REFRESHMENTS_ORDERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.elite.cinema.models.tables.pojos.RefreshmentsOrders fetchOneById(ULong value) {
        return fetchOne(RefreshmentsOrders.REFRESHMENTS_ORDERS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.elite.cinema.models.tables.pojos.RefreshmentsOrders> fetchOptionalById(ULong value) {
        return fetchOptional(RefreshmentsOrders.REFRESHMENTS_ORDERS.ID, value);
    }

    /**
     * Fetch records that have <code>total BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.RefreshmentsOrders> fetchRangeOfTotal(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(RefreshmentsOrders.REFRESHMENTS_ORDERS.TOTAL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>total IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.RefreshmentsOrders> fetchByTotal(ULong... values) {
        return fetch(RefreshmentsOrders.REFRESHMENTS_ORDERS.TOTAL, values);
    }
}
