/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.daos;


import com.elite.cinema.models.tables.ReservedSeats;
import com.elite.cinema.models.tables.records.ReservedSeatsRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.Record3;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReservedSeatsDao extends DAOImpl<ReservedSeatsRecord, com.elite.cinema.models.tables.pojos.ReservedSeats, Record3<ULong, UByte, UByte>> {

    /**
     * Create a new ReservedSeatsDao without any configuration
     */
    public ReservedSeatsDao() {
        super(ReservedSeats.RESERVED_SEATS, com.elite.cinema.models.tables.pojos.ReservedSeats.class);
    }

    /**
     * Create a new ReservedSeatsDao with an attached configuration
     */
    public ReservedSeatsDao(Configuration configuration) {
        super(ReservedSeats.RESERVED_SEATS, com.elite.cinema.models.tables.pojos.ReservedSeats.class, configuration);
    }

    @Override
    public Record3<ULong, UByte, UByte> getId(com.elite.cinema.models.tables.pojos.ReservedSeats object) {
        return compositeKeyRecord(object.getReservationId(), object.getRow(), object.getColumn());
    }

    /**
     * Fetch records that have <code>reservation_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.ReservedSeats> fetchRangeOfReservationId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(ReservedSeats.RESERVED_SEATS.RESERVATION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>reservation_id IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.ReservedSeats> fetchByReservationId(ULong... values) {
        return fetch(ReservedSeats.RESERVED_SEATS.RESERVATION_ID, values);
    }

    /**
     * Fetch records that have <code>row BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.ReservedSeats> fetchRangeOfRow(UByte lowerInclusive, UByte upperInclusive) {
        return fetchRange(ReservedSeats.RESERVED_SEATS.ROW, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>row IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.ReservedSeats> fetchByRow(UByte... values) {
        return fetch(ReservedSeats.RESERVED_SEATS.ROW, values);
    }

    /**
     * Fetch records that have <code>column BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.ReservedSeats> fetchRangeOfColumn(UByte lowerInclusive, UByte upperInclusive) {
        return fetchRange(ReservedSeats.RESERVED_SEATS.COLUMN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>column IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.ReservedSeats> fetchByColumn(UByte... values) {
        return fetch(ReservedSeats.RESERVED_SEATS.COLUMN, values);
    }
}
