/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.daos;


import com.elite.cinema.models.tables.Reservations;
import com.elite.cinema.models.tables.records.ReservationsRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReservationsDao extends DAOImpl<ReservationsRecord, com.elite.cinema.models.tables.pojos.Reservations, ULong> {

    /**
     * Create a new ReservationsDao without any configuration
     */
    public ReservationsDao() {
        super(Reservations.RESERVATIONS, com.elite.cinema.models.tables.pojos.Reservations.class);
    }

    /**
     * Create a new ReservationsDao with an attached configuration
     */
    public ReservationsDao(Configuration configuration) {
        super(Reservations.RESERVATIONS, com.elite.cinema.models.tables.pojos.Reservations.class, configuration);
    }

    @Override
    public ULong getId(com.elite.cinema.models.tables.pojos.Reservations object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Reservations> fetchRangeOfId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(Reservations.RESERVATIONS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Reservations> fetchById(ULong... values) {
        return fetch(Reservations.RESERVATIONS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.elite.cinema.models.tables.pojos.Reservations fetchOneById(ULong value) {
        return fetchOne(Reservations.RESERVATIONS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.elite.cinema.models.tables.pojos.Reservations> fetchOptionalById(ULong value) {
        return fetchOptional(Reservations.RESERVATIONS.ID, value);
    }

    /**
     * Fetch records that have <code>screening_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Reservations> fetchRangeOfScreeningId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(Reservations.RESERVATIONS.SCREENING_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>screening_id IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Reservations> fetchByScreeningId(ULong... values) {
        return fetch(Reservations.RESERVATIONS.SCREENING_ID, values);
    }

    /**
     * Fetch records that have <code>total BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Reservations> fetchRangeOfTotal(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(Reservations.RESERVATIONS.TOTAL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>total IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Reservations> fetchByTotal(UInteger... values) {
        return fetch(Reservations.RESERVATIONS.TOTAL, values);
    }

    /**
     * Fetch records that have <code>paid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Reservations> fetchRangeOfPaid(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(Reservations.RESERVATIONS.PAID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>paid IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Reservations> fetchByPaid(Boolean... values) {
        return fetch(Reservations.RESERVATIONS.PAID, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Reservations> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Reservations.RESERVATIONS.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Reservations> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(Reservations.RESERVATIONS.CREATED_AT, values);
    }
}
