/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.daos;


import com.elite.cinema.models.enums.ScreeningsDisplayType;
import com.elite.cinema.models.enums.ScreeningsTranslationType;
import com.elite.cinema.models.tables.Screenings;
import com.elite.cinema.models.tables.records.ScreeningsRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScreeningsDao extends DAOImpl<ScreeningsRecord, com.elite.cinema.models.tables.pojos.Screenings, ULong> {

    /**
     * Create a new ScreeningsDao without any configuration
     */
    public ScreeningsDao() {
        super(Screenings.SCREENINGS, com.elite.cinema.models.tables.pojos.Screenings.class);
    }

    /**
     * Create a new ScreeningsDao with an attached configuration
     */
    public ScreeningsDao(Configuration configuration) {
        super(Screenings.SCREENINGS, com.elite.cinema.models.tables.pojos.Screenings.class, configuration);
    }

    @Override
    public ULong getId(com.elite.cinema.models.tables.pojos.Screenings object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Screenings> fetchRangeOfId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(Screenings.SCREENINGS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Screenings> fetchById(ULong... values) {
        return fetch(Screenings.SCREENINGS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.elite.cinema.models.tables.pojos.Screenings fetchOneById(ULong value) {
        return fetchOne(Screenings.SCREENINGS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.elite.cinema.models.tables.pojos.Screenings> fetchOptionalById(ULong value) {
        return fetchOptional(Screenings.SCREENINGS.ID, value);
    }

    /**
     * Fetch records that have <code>movie_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Screenings> fetchRangeOfMovieId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(Screenings.SCREENINGS.MOVIE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>movie_id IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Screenings> fetchByMovieId(ULong... values) {
        return fetch(Screenings.SCREENINGS.MOVIE_ID, values);
    }

    /**
     * Fetch records that have <code>room_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Screenings> fetchRangeOfRoomId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(Screenings.SCREENINGS.ROOM_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>room_id IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Screenings> fetchByRoomId(ULong... values) {
        return fetch(Screenings.SCREENINGS.ROOM_ID, values);
    }

    /**
     * Fetch records that have <code>screening_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Screenings> fetchRangeOfScreeningTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Screenings.SCREENINGS.SCREENING_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>screening_time IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Screenings> fetchByScreeningTime(LocalDateTime... values) {
        return fetch(Screenings.SCREENINGS.SCREENING_TIME, values);
    }

    /**
     * Fetch records that have <code>display_type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Screenings> fetchRangeOfDisplayType(ScreeningsDisplayType lowerInclusive, ScreeningsDisplayType upperInclusive) {
        return fetchRange(Screenings.SCREENINGS.DISPLAY_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>display_type IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Screenings> fetchByDisplayType(ScreeningsDisplayType... values) {
        return fetch(Screenings.SCREENINGS.DISPLAY_TYPE, values);
    }

    /**
     * Fetch records that have <code>translation_type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Screenings> fetchRangeOfTranslationType(ScreeningsTranslationType lowerInclusive, ScreeningsTranslationType upperInclusive) {
        return fetchRange(Screenings.SCREENINGS.TRANSLATION_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>translation_type IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Screenings> fetchByTranslationType(ScreeningsTranslationType... values) {
        return fetch(Screenings.SCREENINGS.TRANSLATION_TYPE, values);
    }
}
