/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.daos;


import com.elite.cinema.models.tables.ScreeningRooms;
import com.elite.cinema.models.tables.records.ScreeningRoomsRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScreeningRoomsDao extends DAOImpl<ScreeningRoomsRecord, com.elite.cinema.models.tables.pojos.ScreeningRooms, ULong> {

    /**
     * Create a new ScreeningRoomsDao without any configuration
     */
    public ScreeningRoomsDao() {
        super(ScreeningRooms.SCREENING_ROOMS, com.elite.cinema.models.tables.pojos.ScreeningRooms.class);
    }

    /**
     * Create a new ScreeningRoomsDao with an attached configuration
     */
    public ScreeningRoomsDao(Configuration configuration) {
        super(ScreeningRooms.SCREENING_ROOMS, com.elite.cinema.models.tables.pojos.ScreeningRooms.class, configuration);
    }

    @Override
    public ULong getId(com.elite.cinema.models.tables.pojos.ScreeningRooms object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.ScreeningRooms> fetchRangeOfId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(ScreeningRooms.SCREENING_ROOMS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.ScreeningRooms> fetchById(ULong... values) {
        return fetch(ScreeningRooms.SCREENING_ROOMS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.elite.cinema.models.tables.pojos.ScreeningRooms fetchOneById(ULong value) {
        return fetchOne(ScreeningRooms.SCREENING_ROOMS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.elite.cinema.models.tables.pojos.ScreeningRooms> fetchOptionalById(ULong value) {
        return fetchOptional(ScreeningRooms.SCREENING_ROOMS.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.ScreeningRooms> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(ScreeningRooms.SCREENING_ROOMS.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.ScreeningRooms> fetchByName(String... values) {
        return fetch(ScreeningRooms.SCREENING_ROOMS.NAME, values);
    }
}
