/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.tables.daos;


import com.elite.cinema.models.tables.Seats;
import com.elite.cinema.models.tables.records.SeatsRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SeatsDao extends DAOImpl<SeatsRecord, com.elite.cinema.models.tables.pojos.Seats, UInteger> {

    /**
     * Create a new SeatsDao without any configuration
     */
    public SeatsDao() {
        super(Seats.SEATS, com.elite.cinema.models.tables.pojos.Seats.class);
    }

    /**
     * Create a new SeatsDao with an attached configuration
     */
    public SeatsDao(Configuration configuration) {
        super(Seats.SEATS, com.elite.cinema.models.tables.pojos.Seats.class, configuration);
    }

    @Override
    public UInteger getId(com.elite.cinema.models.tables.pojos.Seats object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Seats> fetchRangeOfId(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(Seats.SEATS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Seats> fetchById(UInteger... values) {
        return fetch(Seats.SEATS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.elite.cinema.models.tables.pojos.Seats fetchOneById(UInteger value) {
        return fetchOne(Seats.SEATS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.elite.cinema.models.tables.pojos.Seats> fetchOptionalById(UInteger value) {
        return fetchOptional(Seats.SEATS.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Seats> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Seats.SEATS.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Seats> fetchByName(String... values) {
        return fetch(Seats.SEATS.NAME, values);
    }

    /**
     * Fetch a unique record that has <code>name = value</code>
     */
    public com.elite.cinema.models.tables.pojos.Seats fetchOneByName(String value) {
        return fetchOne(Seats.SEATS.NAME, value);
    }

    /**
     * Fetch a unique record that has <code>name = value</code>
     */
    public Optional<com.elite.cinema.models.tables.pojos.Seats> fetchOptionalByName(String value) {
        return fetchOptional(Seats.SEATS.NAME, value);
    }

    /**
     * Fetch records that have <code>price BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Seats> fetchRangeOfPrice(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(Seats.SEATS.PRICE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>price IN (values)</code>
     */
    public List<com.elite.cinema.models.tables.pojos.Seats> fetchByPrice(ULong... values) {
        return fetch(Seats.SEATS.PRICE, values);
    }
}
