/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models;


import com.elite.cinema.models.tables.Movies;
import com.elite.cinema.models.tables.Refreshments;
import com.elite.cinema.models.tables.RefreshmentsOrderDetails;
import com.elite.cinema.models.tables.RefreshmentsOrders;
import com.elite.cinema.models.tables.Reservations;
import com.elite.cinema.models.tables.ReservedSeats;
import com.elite.cinema.models.tables.Revenues;
import com.elite.cinema.models.tables.ScreeningRooms;
import com.elite.cinema.models.tables.Screenings;
import com.elite.cinema.models.tables.Seats;
import com.elite.cinema.models.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Cinema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cinema</code>
     */
    public static final Cinema CINEMA = new Cinema();

    /**
     * The table <code>cinema.movies</code>.
     */
    public final Movies MOVIES = Movies.MOVIES;

    /**
     * The table <code>cinema.refreshments</code>.
     */
    public final Refreshments REFRESHMENTS = Refreshments.REFRESHMENTS;

    /**
     * The table <code>cinema.refreshments_order_details</code>.
     */
    public final RefreshmentsOrderDetails REFRESHMENTS_ORDER_DETAILS = RefreshmentsOrderDetails.REFRESHMENTS_ORDER_DETAILS;

    /**
     * The table <code>cinema.refreshments_orders</code>.
     */
    public final RefreshmentsOrders REFRESHMENTS_ORDERS = RefreshmentsOrders.REFRESHMENTS_ORDERS;

    /**
     * The table <code>cinema.reservations</code>.
     */
    public final Reservations RESERVATIONS = Reservations.RESERVATIONS;

    /**
     * The table <code>cinema.reserved_seats</code>.
     */
    public final ReservedSeats RESERVED_SEATS = ReservedSeats.RESERVED_SEATS;

    /**
     * The table <code>cinema.revenues</code>.
     */
    public final Revenues REVENUES = Revenues.REVENUES;

    /**
     * The table <code>cinema.screening_rooms</code>.
     */
    public final ScreeningRooms SCREENING_ROOMS = ScreeningRooms.SCREENING_ROOMS;

    /**
     * The table <code>cinema.screenings</code>.
     */
    public final Screenings SCREENINGS = Screenings.SCREENINGS;

    /**
     * The table <code>cinema.seats</code>.
     */
    public final Seats SEATS = Seats.SEATS;

    /**
     * The table <code>cinema.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Cinema() {
        super(DSL.name("cinema"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Movies.MOVIES,
            Refreshments.REFRESHMENTS,
            RefreshmentsOrderDetails.REFRESHMENTS_ORDER_DETAILS,
            RefreshmentsOrders.REFRESHMENTS_ORDERS,
            Reservations.RESERVATIONS,
            ReservedSeats.RESERVED_SEATS,
            Revenues.REVENUES,
            ScreeningRooms.SCREENING_ROOMS,
            Screenings.SCREENINGS,
            Seats.SEATS,
            Users.USERS
        );
    }
}
