/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models;


import com.elite.cinema.models.tables.MovieInformations;
import com.elite.cinema.models.tables.Movies;
import com.elite.cinema.models.tables.ScreeningRooms;
import com.elite.cinema.models.tables.Screenings;
import com.elite.cinema.models.tables.Users;


/**
 * Convenience access to all tables in cinema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>cinema.movie_informations</code>.
     */
    public static final MovieInformations MOVIE_INFORMATIONS = MovieInformations.MOVIE_INFORMATIONS;

    /**
     * The table <code>cinema.movies</code>.
     */
    public static final Movies MOVIES = Movies.MOVIES;

    /**
     * The table <code>cinema.screening_rooms</code>.
     */
    public static final ScreeningRooms SCREENING_ROOMS = ScreeningRooms.SCREENING_ROOMS;

    /**
     * The table <code>cinema.screenings</code>.
     */
    public static final Screenings SCREENINGS = Screenings.SCREENINGS;

    /**
     * The table <code>cinema.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
