/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models;


import com.elite.cinema.models.tables.Movies;
import com.elite.cinema.models.tables.Refreshments;
import com.elite.cinema.models.tables.RefreshmentsOrderDetails;
import com.elite.cinema.models.tables.RefreshmentsOrders;
import com.elite.cinema.models.tables.Reservations;
import com.elite.cinema.models.tables.ReservedSeats;
import com.elite.cinema.models.tables.ScreeningRooms;
import com.elite.cinema.models.tables.Screenings;
import com.elite.cinema.models.tables.Seats;
import com.elite.cinema.models.tables.Users;


/**
 * Convenience access to all tables in cinema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>cinema.movies</code>.
     */
    public static final Movies MOVIES = Movies.MOVIES;

    /**
     * The table <code>cinema.refreshments</code>.
     */
    public static final Refreshments REFRESHMENTS = Refreshments.REFRESHMENTS;

    /**
     * The table <code>cinema.refreshments_order_details</code>.
     */
    public static final RefreshmentsOrderDetails REFRESHMENTS_ORDER_DETAILS = RefreshmentsOrderDetails.REFRESHMENTS_ORDER_DETAILS;

    /**
     * The table <code>cinema.refreshments_orders</code>.
     */
    public static final RefreshmentsOrders REFRESHMENTS_ORDERS = RefreshmentsOrders.REFRESHMENTS_ORDERS;

    /**
     * The table <code>cinema.reservations</code>.
     */
    public static final Reservations RESERVATIONS = Reservations.RESERVATIONS;

    /**
     * The table <code>cinema.reserved_seats</code>.
     */
    public static final ReservedSeats RESERVED_SEATS = ReservedSeats.RESERVED_SEATS;

    /**
     * The table <code>cinema.screening_rooms</code>.
     */
    public static final ScreeningRooms SCREENING_ROOMS = ScreeningRooms.SCREENING_ROOMS;

    /**
     * The table <code>cinema.screenings</code>.
     */
    public static final Screenings SCREENINGS = Screenings.SCREENINGS;

    /**
     * The table <code>cinema.seats</code>.
     */
    public static final Seats SEATS = Seats.SEATS;

    /**
     * The table <code>cinema.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
