/*
 * This file is generated by jOOQ.
 */
package com.elite.cinema.models.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum ScreeningsDisplayType implements EnumType {

    _2D("2D"),

    _3D("3D");

    private final String literal;

    private ScreeningsDisplayType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static ScreeningsDisplayType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(ScreeningsDisplayType.class, literal);
    }
}
